// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as filesystem$0 from "../filesystem/models.js";

/**
 * EditorState captures open files and the active tab.
 */
export class EditorState {
    "activeFilePath": string;
    "openFiles": FileState[];

    /** Creates a new EditorState instance. */
    constructor($$source: Partial<EditorState> = {}) {
        if (!("activeFilePath" in $$source)) {
            this["activeFilePath"] = "";
        }
        if (!("openFiles" in $$source)) {
            this["openFiles"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EditorState instance from a string or object.
     */
    static createFrom($$source: any = {}): EditorState {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("openFiles" in $$parsedSource) {
            $$parsedSource["openFiles"] = $$createField1_0($$parsedSource["openFiles"]);
        }
        return new EditorState($$parsedSource as Partial<EditorState>);
    }
}

/**
 * Explorer captures file tree expand/collapse state.
 */
export class Explorer {
    "expandedPaths": string[];
    "rootExpanded": boolean;
    "treeSnapshot"?: filesystem$0.FileEntry[];

    /** Creates a new Explorer instance. */
    constructor($$source: Partial<Explorer> = {}) {
        if (!("expandedPaths" in $$source)) {
            this["expandedPaths"] = [];
        }
        if (!("rootExpanded" in $$source)) {
            this["rootExpanded"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Explorer instance from a string or object.
     */
    static createFrom($$source: any = {}): Explorer {
        const $$createField0_0 = $$createType2;
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("expandedPaths" in $$parsedSource) {
            $$parsedSource["expandedPaths"] = $$createField0_0($$parsedSource["expandedPaths"]);
        }
        if ("treeSnapshot" in $$parsedSource) {
            $$parsedSource["treeSnapshot"] = $$createField2_0($$parsedSource["treeSnapshot"]);
        }
        return new Explorer($$parsedSource as Partial<Explorer>);
    }
}

/**
 * FileState captures per-file cursor and scroll position.
 */
export class FileState {
    "path": string;
    "cursorLine": number;
    "cursorColumn": number;
    "scrollTop": number;

    /** Creates a new FileState instance. */
    constructor($$source: Partial<FileState> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("cursorLine" in $$source)) {
            this["cursorLine"] = 0;
        }
        if (!("cursorColumn" in $$source)) {
            this["cursorColumn"] = 0;
        }
        if (!("scrollTop" in $$source)) {
            this["scrollTop"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileState instance from a string or object.
     */
    static createFrom($$source: any = {}): FileState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileState($$parsedSource as Partial<FileState>);
    }
}

/**
 * LSPState holds machine-local LSP overrides for a workspace. Persisted under
 * ~/.firn/workspaces (never in the repo) because interpreter/server paths are
 * machine-specific.
 */
export class LSPState {
    "interpreterOverride"?: string;

    /**
     * family -> path (reserved)
     */
    "serverPathOverride"?: { [_ in string]?: string };

    /** Creates a new LSPState instance. */
    constructor($$source: Partial<LSPState> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LSPState instance from a string or object.
     */
    static createFrom($$source: any = {}): LSPState {
        const $$createField1_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("serverPathOverride" in $$parsedSource) {
            $$parsedSource["serverPathOverride"] = $$createField1_0($$parsedSource["serverPathOverride"]);
        }
        return new LSPState($$parsedSource as Partial<LSPState>);
    }
}

/**
 * Layout captures panel sizes and collapsed states.
 */
export class Layout {
    "panelSizes": PanelSizes;
    "leftCollapsed": boolean;
    "rightCollapsed": boolean;
    "bottomCollapsed": boolean;

    /** Creates a new Layout instance. */
    constructor($$source: Partial<Layout> = {}) {
        if (!("panelSizes" in $$source)) {
            this["panelSizes"] = (new PanelSizes());
        }
        if (!("leftCollapsed" in $$source)) {
            this["leftCollapsed"] = false;
        }
        if (!("rightCollapsed" in $$source)) {
            this["rightCollapsed"] = false;
        }
        if (!("bottomCollapsed" in $$source)) {
            this["bottomCollapsed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Layout instance from a string or object.
     */
    static createFrom($$source: any = {}): Layout {
        const $$createField0_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("panelSizes" in $$parsedSource) {
            $$parsedSource["panelSizes"] = $$createField0_0($$parsedSource["panelSizes"]);
        }
        return new Layout($$parsedSource as Partial<Layout>);
    }
}

/**
 * PanelSizes stores pixel sizes for the three resizable panels.
 */
export class PanelSizes {
    "left": number;
    "right": number;
    "bottom": number;

    /** Creates a new PanelSizes instance. */
    constructor($$source: Partial<PanelSizes> = {}) {
        if (!("left" in $$source)) {
            this["left"] = 0;
        }
        if (!("right" in $$source)) {
            this["right"] = 0;
        }
        if (!("bottom" in $$source)) {
            this["bottom"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PanelSizes instance from a string or object.
     */
    static createFrom($$source: any = {}): PanelSizes {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PanelSizes($$parsedSource as Partial<PanelSizes>);
    }
}

/**
 * State is the complete persisted state for one workspace.
 */
export class State {
    "workspacePath": string;
    "workspaceName": string;

    /**
     * RFC 3339
     */
    "lastOpened": string;
    "layout": Layout;
    "editor": EditorState;
    "explorer": Explorer;
    "activeSidebar": string;
    "hiddenProfileIds"?: string[];
    "activeWorkspaceId"?: string;
    "lsp"?: LSPState;

    /** Creates a new State instance. */
    constructor($$source: Partial<State> = {}) {
        if (!("workspacePath" in $$source)) {
            this["workspacePath"] = "";
        }
        if (!("workspaceName" in $$source)) {
            this["workspaceName"] = "";
        }
        if (!("lastOpened" in $$source)) {
            this["lastOpened"] = "";
        }
        if (!("layout" in $$source)) {
            this["layout"] = (new Layout());
        }
        if (!("editor" in $$source)) {
            this["editor"] = (new EditorState());
        }
        if (!("explorer" in $$source)) {
            this["explorer"] = (new Explorer());
        }
        if (!("activeSidebar" in $$source)) {
            this["activeSidebar"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new State instance from a string or object.
     */
    static createFrom($$source: any = {}): State {
        const $$createField3_0 = $$createType7;
        const $$createField4_0 = $$createType8;
        const $$createField5_0 = $$createType9;
        const $$createField7_0 = $$createType2;
        const $$createField9_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("layout" in $$parsedSource) {
            $$parsedSource["layout"] = $$createField3_0($$parsedSource["layout"]);
        }
        if ("editor" in $$parsedSource) {
            $$parsedSource["editor"] = $$createField4_0($$parsedSource["editor"]);
        }
        if ("explorer" in $$parsedSource) {
            $$parsedSource["explorer"] = $$createField5_0($$parsedSource["explorer"]);
        }
        if ("hiddenProfileIds" in $$parsedSource) {
            $$parsedSource["hiddenProfileIds"] = $$createField7_0($$parsedSource["hiddenProfileIds"]);
        }
        if ("lsp" in $$parsedSource) {
            $$parsedSource["lsp"] = $$createField9_0($$parsedSource["lsp"]);
        }
        return new State($$parsedSource as Partial<State>);
    }
}

/**
 * Summary is a lightweight struct for listing recent workspaces.
 */
export class Summary {
    "name": string;
    "path": string;
    "lastOpened": string;

    /** Creates a new Summary instance. */
    constructor($$source: Partial<Summary> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("lastOpened" in $$source)) {
            this["lastOpened"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Summary instance from a string or object.
     */
    static createFrom($$source: any = {}): Summary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Summary($$parsedSource as Partial<Summary>);
    }
}

/**
 * WorkspaceDef is a detected (or synthetic) focused context within a repo.
 * The synthetic "Project" entry represents the whole repo with a neutral accent.
 */
export class WorkspaceDef {
    /**
     * "project" | relDir | "root:<type>" for root markers
     */
    "id": string;

    /**
     * human label, e.g. "Project", "Frontend"
     */
    "name": string;

    /**
     * "" for project + root-level markers
     */
    "relDir": string;
    "type": WorkspaceType;

    /**
     * Accent is named for the workspace type, 1:1 with Type, and must match a
     * --accent-* token in frontend/src/styles/tokens.css and the WorkspaceAccent
     * union in frontend/src/stores/ideStore.ts.
     * project|frontend|node|python|go|rust|docker|terraform|general
     */
    "accent": string;

    /** Creates a new WorkspaceDef instance. */
    constructor($$source: Partial<WorkspaceDef> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("relDir" in $$source)) {
            this["relDir"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = WorkspaceType.$zero;
        }
        if (!("accent" in $$source)) {
            this["accent"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceDef instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceDef {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceDef($$parsedSource as Partial<WorkspaceDef>);
    }
}

/**
 * WorkspaceType identifies the kind of a detected workspace.
 */
export enum WorkspaceType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TypeProject = "project",
    TypeFrontend = "frontend",
    TypeNode = "node",
    TypeGo = "go",
    TypePython = "python",
    TypeDocker = "docker",
    TypeTerraform = "terraform",

    /**
     * reserved; no marker produces it yet
     */
    TypeGeneral = "general",
};

// Private type creation functions
const $$createType0 = FileState.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = filesystem$0.FileEntry.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
const $$createType6 = PanelSizes.createFrom;
const $$createType7 = Layout.createFrom;
const $$createType8 = EditorState.createFrom;
const $$createType9 = Explorer.createFrom;
const $$createType10 = LSPState.createFrom;
