// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App represents the main application structure for Firn IDE.
 * It holds the application context for Wails runtime interactions.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ai$0 from "./internal/ai/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as filesystem$0 from "./internal/filesystem/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as git$0 from "./internal/git/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as lsp$0 from "./internal/lsp/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as runhistory$0 from "./internal/runhistory/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as runprofile$0 from "./internal/runprofile/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as search$0 from "./internal/search/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as workspace$0 from "./internal/workspace/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AdoptRunProfile adds a profile to its workspace working set and emits an update.
 * This is exposed to the frontend via Wails bindings.
 */
export function AdoptRunProfile(id: string): $CancellablePromise<void> {
    return $Call.ByID(1163939371, id);
}

/**
 * AppendRunHistoryRecord persists a terminal run for the active workspace.
 */
export function AppendRunHistoryRecord(record: runhistory$0.RecordInput): $CancellablePromise<runhistory$0.Summary> {
    return $Call.ByID(3510223835, record).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ApplyGolemSettings is Call 1 of the §5.2 write handshake against the existing
 * configuration target. The request carries the staged changes and, for
 * provider-key operations, the literal key values; those are applied and
 * dropped, and never appear in the result, an event, or a log line. Every
 * outcome — including a refusal — is a closed §5.6 domain result; only a
 * missing service is an error.
 * This is exposed to the frontend via Wails bindings.
 */
export function ApplyGolemSettings(req: ai$0.SettingsApplyRequest): $CancellablePromise<ai$0.SettingsApplyResult> {
    return $Call.ByID(3398837476, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CancelBeforeClose abandons a pending close and returns the machine to idle.
 * Nothing has been torn down at this point, so there is nothing to restore:
 * run admission, searches, the Golem service, and the language servers were
 * never touched. Idempotent, and a no-op once draining has begun.
 * This is exposed to the frontend via Wails bindings.
 */
export function CancelBeforeClose(): $CancellablePromise<void> {
    return $Call.ByID(1449175648);
}

/**
 * CancelGolemRun cancels the run named by identity, or declines its pending
 * consent challenge. It reports whether anything matched.
 * This is exposed to the frontend via Wails bindings.
 */
export function CancelGolemRun(identity: ai$0.RunIdentity): $CancellablePromise<boolean> {
    return $Call.ByID(1666583798, identity);
}

/**
 * CancelGolemSettingsApply invalidates one issued challenge. It is idempotent:
 * an absent, expired, or already consumed token is already cancelled, so the
 * single success variant is the only domain outcome.
 * This is exposed to the frontend via Wails bindings.
 */
export function CancelGolemSettingsApply(challengeToken: string): $CancellablePromise<ai$0.CancelSettingsApplyResult> {
    return $Call.ByID(3715274072, challengeToken).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * CancelSearch aborts an in-flight search by RequestID. It is a no-op when
 * no search with that id is active, which is the expected state after a
 * successful response was already delivered.
 * This is exposed to the frontend via Wails bindings.
 */
export function CancelSearch(requestID: string): $CancellablePromise<void> {
    return $Call.ByID(3924001275, requestID);
}

/**
 * ClearAllRunHistory durably redacts all active-workspace records.
 */
export function ClearAllRunHistory(): $CancellablePromise<void> {
    return $Call.ByID(163211414);
}

/**
 * ClearRunHistoryRecord durably redacts one active-workspace record.
 */
export function ClearRunHistoryRecord(historyID: string): $CancellablePromise<void> {
    return $Call.ByID(1914894684, historyID);
}

/**
 * CloseTerminal terminates the terminal session and removes it from the manager.
 * This is exposed to the frontend via Wails bindings.
 */
export function CloseTerminal(id: string): $CancellablePromise<void> {
    return $Call.ByID(2702963191, id);
}

/**
 * ConfirmBeforeCloseReady signals that the frontend finished its close
 * preparation — settings writes settled, secrets cleared, state flushed — and
 * the app may tear down. It is the only ordinary way into draining, it starts
 * the teardown exactly once, and it is a no-op when no close is pending.
 * This is exposed to the frontend via Wails bindings.
 */
export function ConfirmBeforeCloseReady(): $CancellablePromise<void> {
    return $Call.ByID(1200012883);
}

/**
 * ConfirmGolemSettingsApply is Call 2: the frontend resends the complete
 * request alongside the opaque challenge token, because Call 1 retained none of
 * it. One binding serves both entry points — the operation kind comes from the
 * challenge record, not from the caller.
 * This is exposed to the frontend via Wails bindings.
 */
export function ConfirmGolemSettingsApply(req: ai$0.ConfirmSettingsApplyRequest): $CancellablePromise<ai$0.SettingsApplyResult> {
    return $Call.ByID(4278120228, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CreateGolemSettings is Call 1 for a missing target: the backend derives the
 * destination itself, so no path crosses the boundary in either direction.
 * This is exposed to the frontend via Wails bindings.
 */
export function CreateGolemSettings(req: ai$0.SettingsApplyRequest): $CancellablePromise<ai$0.SettingsApplyResult> {
    return $Call.ByID(649660458, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CreateTerminal creates a new terminal whose shell starts in dir — the loaded
 * workspace root — instead of the app process's own working directory. An
 * empty or missing dir inherits the process default.
 * This is exposed to the frontend via Wails bindings.
 */
export function CreateTerminal(dir: string): $CancellablePromise<string> {
    return $Call.ByID(2206554641, dir);
}

/**
 * DeleteRunProfile removes a saved run profile by ID, emitting runprofiles:changed
 * on success. This is exposed to the frontend via Wails bindings.
 */
export function DeleteRunProfile(id: string): $CancellablePromise<void> {
    return $Call.ByID(2366146988, id);
}

/**
 * DetectRunProfiles re-runs auto-detection and returns detected profiles.
 * This is exposed to the frontend via Wails bindings.
 */
export function DetectRunProfiles(): $CancellablePromise<runprofile$0.RunProfile[]> {
    return $Call.ByID(694773045).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * DetectWorkspaces scans the repo at repoPath for focused workspaces.
 * Returns the synthetic "Project" entry followed by detected workspaces.
 */
export function DetectWorkspaces(repoPath: string): $CancellablePromise<workspace$0.WorkspaceDef[]> {
    return $Call.ByID(3965947368, repoPath).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetAllRunProfiles returns all run profiles (saved + detected, deduplicated).
 * This is exposed to the frontend via Wails bindings.
 */
export function GetAllRunProfiles(): $CancellablePromise<runprofile$0.RunProfile[]> {
    return $Call.ByID(2872107413).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetGolemSettings returns the read-only settings projection of the current
 * effective Golem configuration. It carries no filesystem paths, raw JSON,
 * keys, or raw error text; diagnostics travel in-band as allowlisted codes.
 * This is exposed to the frontend via Wails bindings.
 */
export function GetGolemSettings(): $CancellablePromise<ai$0.SettingsProjection> {
    return $Call.ByID(3594143992).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetGolemStatus returns the Golem status for one workspace of the bound
 * repository. Request and response cross the boundary unchanged and neither
 * carries a filesystem path.
 * This is exposed to the frontend via Wails bindings.
 */
export function GetGolemStatus(req: ai$0.StatusRequest): $CancellablePromise<ai$0.Status> {
    return $Call.ByID(107712831, req).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetLSPStatus returns the status of all running language servers.
 * This is exposed to the frontend via Wails bindings.
 */
export function GetLSPStatus(): $CancellablePromise<lsp$0.ServerStatus[]> {
    return $Call.ByID(2864636116).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * GetRunHistoryRecord lazily loads one rich record from the active workspace.
 */
export function GetRunHistoryRecord(historyID: string): $CancellablePromise<runhistory$0.Record> {
    return $Call.ByID(2890056597, historyID).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * GetRunHistorySnapshot returns the active workspace's persisted run summaries.
 */
export function GetRunHistorySnapshot(): $CancellablePromise<runhistory$0.Snapshot> {
    return $Call.ByID(4208353060).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * GetRunProfilesSnapshot returns the combined profile list plus per-profile UI
 * state (adoption + run recency). This is the P2 hydration contract.
 * This is exposed to the frontend via Wails bindings.
 */
export function GetRunProfilesSnapshot(): $CancellablePromise<runprofile$0.RunProfilesSnapshot> {
    return $Call.ByID(3832950134).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * GetRunStatus returns the current run status of a profile. A compound
 * profile's id returns its aggregate status. Returns the retained terminal
 * status if the profile finished but has not been restarted, or RunStateIdle
 * if it is not running and has no retained status.
 * This is exposed to the frontend via Wails bindings.
 */
export function GetRunStatus(profileID: string): $CancellablePromise<runprofile$0.RunStatus> {
    return $Call.ByID(2215828426, profileID).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * GetWatchedPath returns the currently watched path.
 * This is exposed to the frontend via Wails bindings.
 */
export function GetWatchedPath(): $CancellablePromise<string> {
    return $Call.ByID(890330416);
}

/**
 * GetWorkspaceInfo binds repoPath as the current Golem repository and returns
 * its canonical root plus repository identity. An empty repoPath unbinds and
 * returns empty values. Rebinding the same root keeps the epoch; unbinding and
 * binding again advances it, which invalidates every request built on the old
 * one. This is exposed to the frontend via Wails bindings.
 */
export function GetWorkspaceInfo(repoPath: string): $CancellablePromise<$models.WorkspaceInfo> {
    return $Call.ByID(4142035048, repoPath).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * GitApplyConflictSide applies one whole-file side to the working tree without
 * staging, only while the path still matches expectedSourceVersion. The
 * returned version is what the following GitStageConflictResult must present.
 * This is exposed to the frontend via Wails bindings.
 */
export function GitApplyConflictSide(root: string, path: string, side: string, expectedSourceVersion: string): $CancellablePromise<git$0.ConflictGuardResult> {
    return $Call.ByID(537832820, root, path, side, expectedSourceVersion).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * GitApplyHunk stages (reverse=false) or unstages (reverse=true) a single hunk
 * by applying its patch to the index with `git apply --cached`.
 * This is exposed to the frontend via Wails bindings.
 */
export function GitApplyHunk(root: string, patch: string, reverse: boolean): $CancellablePromise<void> {
    return $Call.ByID(3993157097, root, patch, reverse);
}

/**
 * GitBranches lists local branch names.
 * This is exposed to the frontend via Wails bindings.
 */
export function GitBranches(root: string): $CancellablePromise<string[]> {
    return $Call.ByID(294983995, root).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * GitCheckout switches branches, creating the branch first when create is
 * set. Dirty-file overwrite errors surface verbatim.
 * This is exposed to the frontend via Wails bindings.
 */
export function GitCheckout(root: string, branch: string, create: boolean): $CancellablePromise<void> {
    return $Call.ByID(1598126927, root, branch, create);
}

/**
 * GitCommit records staged changes; amend replaces the previous commit.
 * Returns git's summary line for display.
 * This is exposed to the frontend via Wails bindings.
 */
export function GitCommit(root: string, message: string, amend: boolean): $CancellablePromise<string> {
    return $Call.ByID(1971060042, root, message, amend);
}

/**
 * GitCommitMessageAvailable reports whether embedded AI commit-message
 * generation is available.
 * This is exposed to the frontend via Wails bindings.
 */
export function GitCommitMessageAvailable(): $CancellablePromise<boolean> {
    return $Call.ByID(225459324);
}

/**
 * GitConflictSnapshot returns a conflicted file's content, encoding, line
 * endings, and parsed conflict regions in one read, for the merge resolution
 * surface. Binary or too-large files, and malformed markers, return an error so
 * the frontend falls back to the plain conflict playbook.
 * This is exposed to the frontend via Wails bindings.
 */
export function GitConflictSnapshot(root: string, path: string): $CancellablePromise<git$0.ConflictSnapshot> {
    return $Call.ByID(2823404425, root, path).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * GitConflictStages reports which index stages (base/ours/theirs) exist for a
 * conflicted path plus a binary flag, so the frontend can choose a text or
 * whole-file-side resolution UI.
 * This is exposed to the frontend via Wails bindings.
 */
export function GitConflictStages(root: string, path: string): $CancellablePromise<git$0.ConflictStages> {
    return $Call.ByID(3016103446, root, path).then(($result: any) => {
        return $$createType19($result);
    });
}

/**
 * GitConflictState returns one coherent read of a conflicted path — index
 * stages, the text snapshot when the conflict is text-mergeable, the operation
 * heads, and the opaque source version that identifies exactly that state. The
 * merge surface uses it for both open and revalidation, and passes the version
 * back to the guarded mutations below.
 * This is exposed to the frontend via Wails bindings.
 */
export function GitConflictState(root: string, path: string): $CancellablePromise<git$0.ConflictState> {
    return $Call.ByID(2052720634, root, path).then(($result: any) => {
        return $$createType20($result);
    });
}

/**
 * GitFileAtRev returns file content at a revision ("HEAD", ":0" for the
 * index) with binary/too-large flags the diff UI special-cases. Paths new at
 * that revision return empty content for diffing.
 * This is exposed to the frontend via Wails bindings.
 */
export function GitFileAtRev(root: string, rev: string, path: string): $CancellablePromise<git$0.FileContent> {
    return $Call.ByID(378246237, root, rev, path).then(($result: any) => {
        return $$createType21($result);
    });
}

/**
 * GitFileHunks returns the per-hunk breakdown of a file's diff. staged=false
 * yields working-tree-vs-index hunks (stageable); staged=true yields
 * index-vs-HEAD hunks (unstageable). Each hunk carries a standalone patch for
 * GitApplyHunk.
 * This is exposed to the frontend via Wails bindings.
 */
export function GitFileHunks(root: string, path: string, staged: boolean): $CancellablePromise<git$0.FileHunks> {
    return $Call.ByID(2105794102, root, path, staged).then(($result: any) => {
        return $$createType22($result);
    });
}

/**
 * GitGenerateCommitMessage produces a commit message for the staged diff via
 * the embedded golem runtime.
 * This is exposed to the frontend via Wails bindings.
 */
export function GitGenerateCommitMessage(root: string): $CancellablePromise<string> {
    return $Call.ByID(339534784, root);
}

/**
 * GitIntentToAdd marks untracked repo-root-relative paths intent-to-add
 * (git add -N): tracked as empty index blobs, content left unstaged so the
 * file diffs normally and can be staged hunk-by-hunk.
 * This is exposed to the frontend via Wails bindings.
 */
export function GitIntentToAdd(root: string, paths: string[]): $CancellablePromise<void> {
    return $Call.ByID(3175831011, root, paths);
}

/**
 * GitMergeHeads returns the two sides (ours/theirs) and operation type of the
 * in-progress merge, rebase, or cherry-pick, for the resolution card headers.
 * This is exposed to the frontend via Wails bindings.
 */
export function GitMergeHeads(root: string): $CancellablePromise<git$0.MergeHeads> {
    return $Call.ByID(2954081460, root).then(($result: any) => {
        return $$createType23($result);
    });
}

/**
 * GitPull integrates the upstream branch. Conflict output is returned as an
 * error message for the UI.
 * This is exposed to the frontend via Wails bindings.
 */
export function GitPull(root: string): $CancellablePromise<string> {
    return $Call.ByID(3933172764, root);
}

/**
 * GitPush publishes the current branch, setting an origin upstream on the
 * first push of a new branch.
 * This is exposed to the frontend via Wails bindings.
 */
export function GitPush(root: string): $CancellablePromise<string> {
    return $Call.ByID(4036251239, root);
}

/**
 * GitResolveConflictSide finalizes a whole-file conflict by taking one side
 * ("ours" or "theirs"): the side's content is checked out and staged, or the
 * path is removed and its deletion staged when that side is a deletion.
 * This is exposed to the frontend via Wails bindings.
 */
export function GitResolveConflictSide(root: string, path: string, side: string): $CancellablePromise<void> {
    return $Call.ByID(1499399676, root, path, side);
}

/**
 * GitStage adds repo-root-relative paths to the index.
 * This is exposed to the frontend via Wails bindings.
 */
export function GitStage(root: string, paths: string[]): $CancellablePromise<void> {
    return $Call.ByID(1714641439, root, paths);
}

/**
 * GitStageConflictResult stages a conflicted path's working-tree state (content
 * or deletion) only while it still matches expectedSourceVersion. A failed
 * stage mutates nothing, so a retry can reuse the same version.
 * This is exposed to the frontend via Wails bindings.
 */
export function GitStageConflictResult(root: string, path: string, expectedSourceVersion: string): $CancellablePromise<git$0.ConflictGuardResult> {
    return $Call.ByID(3531123084, root, path, expectedSourceVersion).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * GitStatus returns the repository snapshot for the repo containing root.
 * IsRepo=false (with no error) means root is not inside a git repository or
 * git is not installed; the frontend hides git UI in that case.
 * This is exposed to the frontend via Wails bindings.
 */
export function GitStatus(root: string): $CancellablePromise<git$0.RepoStatus> {
    return $Call.ByID(1421317957, root).then(($result: any) => {
        return $$createType24($result);
    });
}

/**
 * GitUnstage removes repo-root-relative paths from the index.
 * This is exposed to the frontend via Wails bindings.
 */
export function GitUnstage(root: string, paths: string[]): $CancellablePromise<void> {
    return $Call.ByID(2384683490, root, paths);
}

/**
 * GitWriteConflictResult writes a resolved text result to the working tree only
 * while the file still matches expectedSourceVersion. Applied=false means the
 * file changed underneath the caller and nothing was written; the returned
 * version is the live one.
 * This is exposed to the frontend via Wails bindings.
 */
export function GitWriteConflictResult(root: string, path: string, expectedSourceVersion: string, content: string, encoding: string, lineEndings: string): $CancellablePromise<git$0.ConflictGuardResult> {
    return $Call.ByID(3476173397, root, path, expectedSourceVersion, content, encoding, lineEndings).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * IsWatching returns true if currently watching a path.
 * This is exposed to the frontend via Wails bindings.
 */
export function IsWatching(): $CancellablePromise<boolean> {
    return $Call.ByID(1084708984);
}

/**
 * LSPClearInterpreter removes the override and re-detects.
 * This is exposed to the frontend via Wails bindings.
 */
export function LSPClearInterpreter(workspacePath: string): $CancellablePromise<void> {
    return $Call.ByID(1973317877, workspacePath);
}

/**
 * LSPComplete requests completion items for a position in a document.
 * This is exposed to the frontend via Wails bindings.
 */
export function LSPComplete(path: string, line: number, character: number, triggerCharacter: string): $CancellablePromise<lsp$0.CompletionList | null> {
    return $Call.ByID(1096608999, path, line, character, triggerCharacter).then(($result: any) => {
        return $$createType26($result);
    });
}

/**
 * LSPDefinition requests go-to-definition for a position in a document.
 * This is exposed to the frontend via Wails bindings.
 */
export function LSPDefinition(path: string, line: number, character: number): $CancellablePromise<lsp$0.Location[]> {
    return $Call.ByID(1220397137, path, line, character).then(($result: any) => {
        return $$createType28($result);
    });
}

/**
 * LSPDidChange notifies the LSP manager that a document changed.
 * This is exposed to the frontend via Wails bindings.
 */
export function LSPDidChange(path: string, version: number, contentChanges: lsp$0.TextDocumentContentChangeEvent[]): $CancellablePromise<void> {
    return $Call.ByID(3202021105, path, version, contentChanges);
}

/**
 * LSPDidClose notifies the LSP manager that a document was closed.
 * This is exposed to the frontend via Wails bindings.
 */
export function LSPDidClose(path: string): $CancellablePromise<void> {
    return $Call.ByID(2096960191, path);
}

/**
 * LSPDidOpen notifies the LSP manager that a document was opened.
 * The frontend is the source of truth for version numbers.
 * This is exposed to the frontend via Wails bindings.
 */
export function LSPDidOpen(path: string, languageID: string, version: number, content: string): $CancellablePromise<void> {
    return $Call.ByID(1696173437, path, languageID, version, content);
}

/**
 * LSPDidSave notifies the LSP manager that a document was saved.
 * This is exposed to the frontend via Wails bindings.
 */
export function LSPDidSave(path: string): $CancellablePromise<void> {
    return $Call.ByID(1230897924, path);
}

/**
 * LSPDoctor returns interpreter candidates + current override for a workspace.
 * This is exposed to the frontend via Wails bindings.
 */
export function LSPDoctor(workspacePath: string): $CancellablePromise<lsp$0.DoctorReport> {
    return $Call.ByID(4202333507, workspacePath).then(($result: any) => {
        return $$createType29($result);
    });
}

/**
 * LSPDocumentSymbol requests the document symbols (structure/outline) for a file.
 * This is exposed to the frontend via Wails bindings.
 */
export function LSPDocumentSymbol(path: string): $CancellablePromise<lsp$0.DocumentSymbol[]> {
    return $Call.ByID(1714560845, path).then(($result: any) => {
        return $$createType31($result);
    });
}

/**
 * LSPHover requests hover information for a position in a document.
 * This is exposed to the frontend via Wails bindings.
 */
export function LSPHover(path: string, line: number, character: number): $CancellablePromise<lsp$0.Hover | null> {
    return $Call.ByID(2120599106, path, line, character).then(($result: any) => {
        return $$createType33($result);
    });
}

/**
 * LSPResolveCompletionItem requests additional detail for a completion item.
 * This is exposed to the frontend via Wails bindings.
 */
export function LSPResolveCompletionItem(path: string, item: lsp$0.CompletionItem): $CancellablePromise<lsp$0.CompletionItem | null> {
    return $Call.ByID(1353444265, path, item).then(($result: any) => {
        return $$createType35($result);
    });
}

/**
 * LSPRetryProvision re-attempts a managed server install for a family, keyed
 * to the project root the failing status reported (empty falls back to the
 * workspace root).
 * This is exposed to the frontend via Wails bindings.
 */
export function LSPRetryProvision(family: string, projectRoot: string): $CancellablePromise<void> {
    return $Call.ByID(3623936149, family, projectRoot);
}

/**
 * LSPSetInterpreter validates + persists a manual interpreter override for the
 * workspace and re-wires/restarts the affected server.
 * This is exposed to the frontend via Wails bindings.
 */
export function LSPSetInterpreter(workspacePath: string, interpreterPath: string): $CancellablePromise<void> {
    return $Call.ByID(3837696518, workspacePath, interpreterPath);
}

/**
 * ListRecentWorkspaces returns summaries of recently opened workspaces.
 * This is exposed to the frontend via Wails bindings.
 */
export function ListRecentWorkspaces(): $CancellablePromise<workspace$0.Summary[]> {
    return $Call.ByID(3459539712).then(($result: any) => {
        return $$createType37($result);
    });
}

/**
 * LoadGolemProfile returns one profile's credential-free draft preview plus the
 * provenance a profile-origin Apply must send back. The loader clears every
 * provider key before anything reads the document, so no profile secret can
 * reach this result. The service guard is the same one the other Golem
 * bindings use: a profile draft is useless without a service to apply it to,
 * and a.ctx exists exactly when that service does.
 * This is exposed to the frontend via Wails bindings.
 */
export function LoadGolemProfile(profileID: string): $CancellablePromise<ai$0.GolemProfileLoadResult> {
    return $Call.ByID(1561429884, profileID).then(($result: any) => {
        return $$createType38($result);
    });
}

/**
 * LoadRunProfiles initializes or reinitializes the run profile manager for the given workspace path.
 * If switching workspaces while profiles are running, stops all running profiles first.
 * This is exposed to the frontend via Wails bindings.
 */
export function LoadRunProfiles(workspacePath: string): $CancellablePromise<void> {
    return $Call.ByID(1028400400, workspacePath);
}

/**
 * LoadWorkspaceState loads saved state for a workspace path.
 * Returns nil if no saved state exists (first time opening).
 * This is exposed to the frontend via Wails bindings.
 */
export function LoadWorkspaceState(workspacePath: string): $CancellablePromise<workspace$0.State | null> {
    return $Call.ByID(2334223351, workspacePath).then(($result: any) => {
        return $$createType40($result);
    });
}

/**
 * OpenFolderDialog opens a native folder picker dialog.
 * Returns the selected folder path, or empty string if cancelled.
 * This is exposed to the frontend via Wails bindings.
 */
export function OpenFolderDialog(): $CancellablePromise<string> {
    return $Call.ByID(1898277525);
}

/**
 * PinRunProfile converts a detected profile to a saved profile and emits an update event.
 * This is exposed to the frontend via Wails bindings.
 */
export function PinRunProfile(id: string): $CancellablePromise<void> {
    return $Call.ByID(3457538554, id);
}

/**
 * ReadDirectory reads a directory and returns its contents as a tree structure.
 * This is exposed to the frontend via Wails bindings.
 */
export function ReadDirectory(path: string): $CancellablePromise<filesystem$0.FileEntry[]> {
    return $Call.ByID(3882613584, path).then(($result: any) => {
        return $$createType42($result);
    });
}

/**
 * ReadDirectoryShallow reads a single directory level (immediate children only).
 * Used for lazy tree loading — child directories are returned without their
 * own children populated.
 */
export function ReadDirectoryShallow(path: string, rootPath: string): $CancellablePromise<filesystem$0.FileEntry[]> {
    return $Call.ByID(1781218628, path, rootPath).then(($result: any) => {
        return $$createType42($result);
    });
}

/**
 * ReadFile reads a file and returns its contents with metadata.
 * Detects encoding (UTF-8, UTF-16, Latin-1) and line endings.
 * This is exposed to the frontend via Wails bindings.
 */
export function ReadFile(path: string): $CancellablePromise<filesystem$0.FileContent | null> {
    return $Call.ByID(1160596971, path).then(($result: any) => {
        return $$createType44($result);
    });
}

/**
 * ReloadGolemSettings rebuilds the effective configuration snapshot under the
 * idle barrier. Busy=true reports a rejected reload with the unchanged
 * current projection.
 * This is exposed to the frontend via Wails bindings.
 */
export function ReloadGolemSettings(): $CancellablePromise<ai$0.SettingsReloadResult> {
    return $Call.ByID(1366669581).then(($result: any) => {
        return $$createType45($result);
    });
}

/**
 * ResizeTerminal passes the new dimensions of the terminal window
 * This is exposed to the frontend via Wails bindings.
 */
export function ResizeTerminal(id: string, rows: number, cols: number): $CancellablePromise<void> {
    return $Call.ByID(1887984285, id, rows, cols);
}

/**
 * RestartRunInstance replaces exactly one selected ordinary execution while
 * leaving same-profile siblings untouched.
 * This is exposed to the frontend via Wails bindings.
 */
export function RestartRunInstance(runInstanceID: string): $CancellablePromise<void> {
    return $Call.ByID(3775013950, runInstanceID);
}

/**
 * RestartRunProfile stops then starts a profile.
 * If the profile is not currently running, it just starts it.
 * Stop, drain, and workspace-epoch errors are propagated; a failed stop or
 * invalid admission never starts a replacement.
 * This is exposed to the frontend via Wails bindings.
 */
export function RestartRunProfile(profileID: string): $CancellablePromise<void> {
    return $Call.ByID(3087697138, profileID);
}

/**
 * RunGolemTurn submits one chat turn for admission. It returns as soon as the
 * turn is accepted or a consent decision is needed; run output arrives on the
 * golem:event and golem:run-status events.
 * This is exposed to the frontend via Wails bindings.
 */
export function RunGolemTurn(req: ai$0.TurnRequest): $CancellablePromise<ai$0.TurnAdmission> {
    return $Call.ByID(2592072505, req).then(($result: any) => {
        return $$createType46($result);
    });
}

/**
 * SaveRunProfile validates and saves a run profile, emitting runprofiles:changed
 * on a successful, valid save. This is exposed to the frontend via Wails bindings.
 */
export function SaveRunProfile(profile: runprofile$0.RunProfile): $CancellablePromise<runprofile$0.ValidationResult> {
    return $Call.ByID(2441820046, profile).then(($result: any) => {
        return $$createType47($result);
    });
}

/**
 * SaveWorkspaceState saves workspace state for session restore.
 * This is exposed to the frontend via Wails bindings.
 */
export function SaveWorkspaceState(state: workspace$0.State): $CancellablePromise<void> {
    return $Call.ByID(4071643534, state);
}

/**
 * SearchWorkspace runs a workspace text search via ripgrep and returns a
 * typed response. Status discriminates between success, no-matches,
 * missing-tool, invalid-regex, canceled, and failed states; the frontend
 * renders distinct UI for each. The Wails context is passed through so the
 * search aborts when the application context is canceled (window close).
 * This is exposed to the frontend via Wails bindings.
 */
export function SearchWorkspace(request: search$0.SearchRequest): $CancellablePromise<search$0.SearchResponse> {
    return $Call.ByID(99753730, request).then(($result: any) => {
        return $$createType48($result);
    });
}

/**
 * SetActiveVariant selects the env variant for a run profile and emits the updated profile list.
 * This is exposed to the frontend via Wails bindings.
 */
export function SetActiveVariant(profileID: string, variant: string): $CancellablePromise<void> {
    return $Call.ByID(2124903030, profileID, variant);
}

/**
 * SetLSPWorkspaceRoot updates the LSP manager's workspace root.
 * Called when the workspace changes — shuts down old servers first.
 * This is exposed to the frontend via Wails bindings.
 */
export function SetLSPWorkspaceRoot(workspacePath: string): $CancellablePromise<void> {
    return $Call.ByID(1034437419, workspacePath);
}

/**
 * StartRunProfile starts executing a run profile by ID.
 * This is exposed to the frontend via Wails bindings.
 */
export function StartRunProfile(profileID: string): $CancellablePromise<void> {
    return $Call.ByID(2577728021, profileID);
}

/**
 * StartWatching starts watching the given path for file changes.
 * Events are emitted to the frontend via "file:changed" event.
 * This is exposed to the frontend via Wails bindings.
 */
export function StartWatching(path: string): $CancellablePromise<void> {
    return $Call.ByID(2805754466, path);
}

/**
 * StopRunInstance stops exactly one ordinary execution. Unknown or already
 * terminal run IDs are idempotent no-ops.
 * This is exposed to the frontend via Wails bindings.
 */
export function StopRunInstance(runInstanceID: string): $CancellablePromise<void> {
    return $Call.ByID(2861263613, runInstanceID);
}

/**
 * StopRunProfile stops a running profile (SIGTERM → 3s → SIGKILL).
 * The id resolves via the executor's active-run table: a single profile's id
 * stops that run; a compound profile's id cancels the coordinator and stops the
 * current step's leaf; a step profile's own id stops just that leaf (which halts
 * the surrounding compound). An idle/unknown id is a no-op (returns nil).
 * This is exposed to the frontend via Wails bindings.
 */
export function StopRunProfile(profileID: string): $CancellablePromise<void> {
    return $Call.ByID(1594498335, profileID);
}

/**
 * StopWatching stops watching for file changes.
 * This is exposed to the frontend via Wails bindings.
 */
export function StopWatching(): $CancellablePromise<void> {
    return $Call.ByID(3671977832);
}

/**
 * ToggleMaximize toggles the window between maximized and restored states.
 * This is exposed to the frontend via Wails bindings.
 */
export function ToggleMaximize(): $CancellablePromise<void> {
    return $Call.ByID(963143607);
}

/**
 * UnadoptRunProfile removes a profile from its workspace working set and emits an update.
 * This is exposed to the frontend via Wails bindings.
 */
export function UnadoptRunProfile(id: string): $CancellablePromise<void> {
    return $Call.ByID(1791179426, id);
}

/**
 * UnpinRunProfile reverts a saved (pinned) profile back to detected status.
 * This is exposed to the frontend via Wails bindings.
 */
export function UnpinRunProfile(id: string): $CancellablePromise<void> {
    return $Call.ByID(236417819, id);
}

/**
 * ValidateRunProfile validates a run profile without saving it.
 * This is exposed to the frontend via Wails bindings.
 */
export function ValidateRunProfile(profile: runprofile$0.RunProfile): $CancellablePromise<runprofile$0.ValidationResult> {
    return $Call.ByID(162550721, profile).then(($result: any) => {
        return $$createType47($result);
    });
}

/**
 * WriteFile writes content to a file with optional encoding and line ending settings.
 * This is exposed to the frontend via Wails bindings.
 */
export function WriteFile(path: string, content: string, encoding: string, lineEndings: string, createBackup: boolean): $CancellablePromise<void> {
    return $Call.ByID(3562730546, path, content, encoding, lineEndings, createBackup);
}

/**
 * WriteTerminal passes strings from JS
 * This is exposed to the frontend via Wails bindings.
 */
export function WriteTerminal(id: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(146795716, id, data);
}

// Private type creation functions
const $$createType0 = runhistory$0.Summary.createFrom;
const $$createType1 = ai$0.SettingsApplyResult.createFrom;
const $$createType2 = ai$0.CancelSettingsApplyResult.createFrom;
const $$createType3 = runprofile$0.RunProfile.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = workspace$0.WorkspaceDef.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = ai$0.SettingsProjection.createFrom;
const $$createType8 = ai$0.Status.createFrom;
const $$createType9 = lsp$0.ServerStatus.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = runhistory$0.Record.createFrom;
const $$createType12 = runhistory$0.Snapshot.createFrom;
const $$createType13 = runprofile$0.RunProfilesSnapshot.createFrom;
const $$createType14 = runprofile$0.RunStatus.createFrom;
const $$createType15 = $models.WorkspaceInfo.createFrom;
const $$createType16 = git$0.ConflictGuardResult.createFrom;
const $$createType17 = $Create.Array($Create.Any);
const $$createType18 = git$0.ConflictSnapshot.createFrom;
const $$createType19 = git$0.ConflictStages.createFrom;
const $$createType20 = git$0.ConflictState.createFrom;
const $$createType21 = git$0.FileContent.createFrom;
const $$createType22 = git$0.FileHunks.createFrom;
const $$createType23 = git$0.MergeHeads.createFrom;
const $$createType24 = git$0.RepoStatus.createFrom;
const $$createType25 = lsp$0.CompletionList.createFrom;
const $$createType26 = $Create.Nullable($$createType25);
const $$createType27 = lsp$0.Location.createFrom;
const $$createType28 = $Create.Array($$createType27);
const $$createType29 = lsp$0.DoctorReport.createFrom;
const $$createType30 = lsp$0.DocumentSymbol.createFrom;
const $$createType31 = $Create.Array($$createType30);
const $$createType32 = lsp$0.Hover.createFrom;
const $$createType33 = $Create.Nullable($$createType32);
const $$createType34 = lsp$0.CompletionItem.createFrom;
const $$createType35 = $Create.Nullable($$createType34);
const $$createType36 = workspace$0.Summary.createFrom;
const $$createType37 = $Create.Array($$createType36);
const $$createType38 = ai$0.GolemProfileLoadResult.createFrom;
const $$createType39 = workspace$0.State.createFrom;
const $$createType40 = $Create.Nullable($$createType39);
const $$createType41 = filesystem$0.FileEntry.createFrom;
const $$createType42 = $Create.Array($$createType41);
const $$createType43 = filesystem$0.FileContent.createFrom;
const $$createType44 = $Create.Nullable($$createType43);
const $$createType45 = ai$0.SettingsReloadResult.createFrom;
const $$createType46 = ai$0.TurnAdmission.createFrom;
const $$createType47 = runprofile$0.ValidationResult.createFrom;
const $$createType48 = search$0.SearchResponse.createFrom;
