// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * WorkspaceInfo identifies the repository the Golem chat is bound to. Path is
 * the canonical root the backend authorized, never the caller's input, and all
 * four fields are zero when nothing is bound.
 */
export class WorkspaceInfo {
    "name": string;
    "path": string;
    "repoKey": string;
    "repoEpoch": number;

    /** Creates a new WorkspaceInfo instance. */
    constructor($$source: Partial<WorkspaceInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("repoKey" in $$source)) {
            this["repoKey"] = "";
        }
        if (!("repoEpoch" in $$source)) {
            this["repoEpoch"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceInfo($$parsedSource as Partial<WorkspaceInfo>);
    }
}
