// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../encoding/json/models.js";

/**
 * CompletionItem represents a completion suggestion.
 */
export class CompletionItem {
    "label": string;
    "kind"?: CompletionItemKind;
    "detail"?: string;
    "labelDetails"?: CompletionItemLabelDetails | null;
    "documentation"?: json$0.RawMessage;
    "insertText"?: string;
    "insertTextFormat"?: InsertTextFormat;
    "textEdit"?: TextEdit | null;
    "filterText"?: string;
    "sortText"?: string;
    "commitCharacters"?: string[];
    "data"?: json$0.RawMessage;

    /** Creates a new CompletionItem instance. */
    constructor($$source: Partial<CompletionItem> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompletionItem instance from a string or object.
     */
    static createFrom($$source: any = {}): CompletionItem {
        const $$createField3_0 = $$createType1;
        const $$createField7_0 = $$createType3;
        const $$createField10_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("labelDetails" in $$parsedSource) {
            $$parsedSource["labelDetails"] = $$createField3_0($$parsedSource["labelDetails"]);
        }
        if ("textEdit" in $$parsedSource) {
            $$parsedSource["textEdit"] = $$createField7_0($$parsedSource["textEdit"]);
        }
        if ("commitCharacters" in $$parsedSource) {
            $$parsedSource["commitCharacters"] = $$createField10_0($$parsedSource["commitCharacters"]);
        }
        return new CompletionItem($$parsedSource as Partial<CompletionItem>);
    }
}

/**
 * CompletionItemKind defines the kind of a completion entry.
 * The backend passes these through as integers; the frontend maps them to icons/styles.
 */
export type CompletionItemKind = number;

export class CompletionItemLabelDetails {
    "detail"?: string;
    "description"?: string;

    /** Creates a new CompletionItemLabelDetails instance. */
    constructor($$source: Partial<CompletionItemLabelDetails> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompletionItemLabelDetails instance from a string or object.
     */
    static createFrom($$source: any = {}): CompletionItemLabelDetails {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CompletionItemLabelDetails($$parsedSource as Partial<CompletionItemLabelDetails>);
    }
}

/**
 * CompletionList represents a collection of completion items.
 */
export class CompletionList {
    "isIncomplete": boolean;
    "items": CompletionItem[];

    /** Creates a new CompletionList instance. */
    constructor($$source: Partial<CompletionList> = {}) {
        if (!("isIncomplete" in $$source)) {
            this["isIncomplete"] = false;
        }
        if (!("items" in $$source)) {
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompletionList instance from a string or object.
     */
    static createFrom($$source: any = {}): CompletionList {
        const $$createField1_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField1_0($$parsedSource["items"]);
        }
        return new CompletionList($$parsedSource as Partial<CompletionList>);
    }
}

/**
 * DoctorReport summarizes python LSP setup for a workspace so the UI can render
 * actionable choices from one call.
 */
export class DoctorReport {
    "family": string;
    "interpreterPath"?: string;
    "interpreterSource"?: string;
    "override"?: string;
    "candidates": string[];

    /** Creates a new DoctorReport instance. */
    constructor($$source: Partial<DoctorReport> = {}) {
        if (!("family" in $$source)) {
            this["family"] = "";
        }
        if (!("candidates" in $$source)) {
            this["candidates"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DoctorReport instance from a string or object.
     */
    static createFrom($$source: any = {}): DoctorReport {
        const $$createField4_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("candidates" in $$parsedSource) {
            $$parsedSource["candidates"] = $$createField4_0($$parsedSource["candidates"]);
        }
        return new DoctorReport($$parsedSource as Partial<DoctorReport>);
    }
}

/**
 * DocumentSymbol represents a programming construct in a document, such as a
 * class, method, or variable. Symbols can nest via Children when the server
 * supports hierarchical document symbols.
 * 
 * This is the normalized shape Firn works with. Servers that only return the
 * legacy flat SymbolInformation[] are converted into a flat slice of these
 * (no Children) before reaching the manager — see normalizeDocumentSymbols.
 */
export class DocumentSymbol {
    "name": string;
    "detail"?: string;
    "kind": SymbolKind;

    /**
     * Range is the full source range enclosing the symbol (including its body).
     */
    "range": Range;

    /**
     * SelectionRange is the range that should be selected/revealed when the
     * symbol is picked (typically the identifier). Always contained in Range.
     */
    "selectionRange": Range;
    "children"?: DocumentSymbol[];

    /** Creates a new DocumentSymbol instance. */
    constructor($$source: Partial<DocumentSymbol> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = 0;
        }
        if (!("range" in $$source)) {
            this["range"] = (new Range());
        }
        if (!("selectionRange" in $$source)) {
            this["selectionRange"] = (new Range());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocumentSymbol instance from a string or object.
     */
    static createFrom($$source: any = {}): DocumentSymbol {
        const $$createField3_0 = $$createType7;
        const $$createField4_0 = $$createType7;
        const $$createField5_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("range" in $$parsedSource) {
            $$parsedSource["range"] = $$createField3_0($$parsedSource["range"]);
        }
        if ("selectionRange" in $$parsedSource) {
            $$parsedSource["selectionRange"] = $$createField4_0($$parsedSource["selectionRange"]);
        }
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField5_0($$parsedSource["children"]);
        }
        return new DocumentSymbol($$parsedSource as Partial<DocumentSymbol>);
    }
}

/**
 * Hover is the result of a hover request.
 */
export class Hover {
    "contents": json$0.RawMessage;
    "range"?: Range | null;

    /** Creates a new Hover instance. */
    constructor($$source: Partial<Hover> = {}) {
        if (!("contents" in $$source)) {
            this["contents"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Hover instance from a string or object.
     */
    static createFrom($$source: any = {}): Hover {
        const $$createField1_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("range" in $$parsedSource) {
            $$parsedSource["range"] = $$createField1_0($$parsedSource["range"]);
        }
        return new Hover($$parsedSource as Partial<Hover>);
    }
}

/**
 * InsertTextFormat defines whether the insert text is plain text or a snippet.
 * The backend passes these through as integers.
 */
export type InsertTextFormat = number;

/**
 * Location represents a location inside a resource.
 */
export class Location {
    "uri": string;
    "range": Range;

    /** Creates a new Location instance. */
    constructor($$source: Partial<Location> = {}) {
        if (!("uri" in $$source)) {
            this["uri"] = "";
        }
        if (!("range" in $$source)) {
            this["range"] = (new Range());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Location instance from a string or object.
     */
    static createFrom($$source: any = {}): Location {
        const $$createField1_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("range" in $$parsedSource) {
            $$parsedSource["range"] = $$createField1_0($$parsedSource["range"]);
        }
        return new Location($$parsedSource as Partial<Location>);
    }
}

/**
 * Position in a text document expressed as zero-based line and character offset.
 */
export class Position {
    "line": number;
    "character": number;

    /** Creates a new Position instance. */
    constructor($$source: Partial<Position> = {}) {
        if (!("line" in $$source)) {
            this["line"] = 0;
        }
        if (!("character" in $$source)) {
            this["character"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Position instance from a string or object.
     */
    static createFrom($$source: any = {}): Position {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Position($$parsedSource as Partial<Position>);
    }
}

/**
 * Range in a text document expressed as start and end positions.
 */
export class Range {
    "start": Position;
    "end": Position;

    /** Creates a new Range instance. */
    constructor($$source: Partial<Range> = {}) {
        if (!("start" in $$source)) {
            this["start"] = (new Position());
        }
        if (!("end" in $$source)) {
            this["end"] = (new Position());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Range instance from a string or object.
     */
    static createFrom($$source: any = {}): Range {
        const $$createField0_0 = $$createType11;
        const $$createField1_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("start" in $$parsedSource) {
            $$parsedSource["start"] = $$createField0_0($$parsedSource["start"]);
        }
        if ("end" in $$parsedSource) {
            $$parsedSource["end"] = $$createField1_0($$parsedSource["end"]);
        }
        return new Range($$parsedSource as Partial<Range>);
    }
}

/**
 * ServerStatus represents the current status of a language server.
 */
export class ServerStatus {
    "family": string;
    "workspace": string;
    "command"?: string;

    /**
     * "starting", "ready", "stopping", "stopped", "error"
     */
    "state": string;
    "error"?: string;
    "completionTriggerCharacters"?: string[];

    /**
     * ready|missing_server|missing_interpreter|misconfigured_env|config_degraded|retryable|provisioning|offline|provision_failed
     */
    "setupState"?: string;
    "interpreterPath"?: string;
    "projectRoot"?: string;
    "configSource"?: string;
    "extraPaths"?: string[];
    "pythonVersion"?: string;

    /**
     * create_venv|select_interpreter|retry|""
     */
    "action"?: string;
    "detailCode"?: string;

    /**
     * 0-100 during managed install
     */
    "provisionPct"?: number;

    /** Creates a new ServerStatus instance. */
    constructor($$source: Partial<ServerStatus> = {}) {
        if (!("family" in $$source)) {
            this["family"] = "";
        }
        if (!("workspace" in $$source)) {
            this["workspace"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ServerStatus {
        const $$createField5_0 = $$createType4;
        const $$createField10_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("completionTriggerCharacters" in $$parsedSource) {
            $$parsedSource["completionTriggerCharacters"] = $$createField5_0($$parsedSource["completionTriggerCharacters"]);
        }
        if ("extraPaths" in $$parsedSource) {
            $$parsedSource["extraPaths"] = $$createField10_0($$parsedSource["extraPaths"]);
        }
        return new ServerStatus($$parsedSource as Partial<ServerStatus>);
    }
}

/**
 * SymbolKind enumerates the kind of a document symbol per the LSP spec.
 * Values match the protocol's numeric codes (1-26).
 */
export type SymbolKind = number;

/**
 * TextDocumentContentChangeEvent describes textual changes to a document.
 */
export class TextDocumentContentChangeEvent {
    "range"?: Range | null;
    "text": string;

    /** Creates a new TextDocumentContentChangeEvent instance. */
    constructor($$source: Partial<TextDocumentContentChangeEvent> = {}) {
        if (!("text" in $$source)) {
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TextDocumentContentChangeEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): TextDocumentContentChangeEvent {
        const $$createField0_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("range" in $$parsedSource) {
            $$parsedSource["range"] = $$createField0_0($$parsedSource["range"]);
        }
        return new TextDocumentContentChangeEvent($$parsedSource as Partial<TextDocumentContentChangeEvent>);
    }
}

/**
 * TextEdit represents a textual edit applicable to a text document.
 */
export class TextEdit {
    "range": Range;
    "newText": string;

    /** Creates a new TextEdit instance. */
    constructor($$source: Partial<TextEdit> = {}) {
        if (!("range" in $$source)) {
            this["range"] = (new Range());
        }
        if (!("newText" in $$source)) {
            this["newText"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TextEdit instance from a string or object.
     */
    static createFrom($$source: any = {}): TextEdit {
        const $$createField0_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("range" in $$parsedSource) {
            $$parsedSource["range"] = $$createField0_0($$parsedSource["range"]);
        }
        return new TextEdit($$parsedSource as Partial<TextEdit>);
    }
}

// Private type creation functions
const $$createType0 = CompletionItemLabelDetails.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = TextEdit.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = CompletionItem.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = Range.createFrom;
const $$createType8 = DocumentSymbol.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $Create.Nullable($$createType7);
const $$createType11 = Position.createFrom;
