// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ConflictGuardResult reports the outcome of a guarded conflict mutation.
 * Applied=false is the ordinary "someone else changed the file" outcome and
 * mutates nothing; SourceVersion always carries the live version so the caller
 * can re-read or re-confirm. Operational failures are returned as errors
 * instead, so a caller never has to parse error text to tell a race from a
 * broken repository.
 */
export class ConflictGuardResult {
    "applied": boolean;
    "sourceVersion": string;

    /** Creates a new ConflictGuardResult instance. */
    constructor($$source: Partial<ConflictGuardResult> = {}) {
        if (!("applied" in $$source)) {
            this["applied"] = false;
        }
        if (!("sourceVersion" in $$source)) {
            this["sourceVersion"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConflictGuardResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ConflictGuardResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConflictGuardResult($$parsedSource as Partial<ConflictGuardResult>);
    }
}

/**
 * ConflictRegion is one <<<<<<< / ======= / >>>>>>> block in a conflicted
 * working-tree file. Line numbers are 1-based into the file the frontend
 * displays. Ours/Base/Theirs hold the region's lines without their trailing
 * newline (each entry is one line); they are always non-nil slices so a side
 * that resolves to nothing (a delete/modify within the block) is an empty
 * slice, never a JSON null. Base is populated only for diff3-style markers
 * (HasBase); the default merge style omits the ||||||| section. The three
 * EndsWithNewline fields are populated only on a final EOF region from the
 * authoritative stage blobs; nil means that stage is absent.
 */
export class ConflictRegion {
    "index": number;

    /**
     * 1-based line of the <<<<<<< marker
     */
    "startLine": number;

    /**
     * 1-based line of the >>>>>>> marker
     */
    "endLine": number;
    "ours": string[];
    "base": string[];
    "theirs": string[];
    "hasBase": boolean;

    /**
     * text after <<<<<<< (e.g. "HEAD")
     */
    "oursLabel": string;

    /**
     * text after >>>>>>> (e.g. branch name)
     */
    "theirLabel": string;
    "baseEndsWithNewline"?: boolean | null;
    "oursEndsWithNewline"?: boolean | null;
    "theirsEndsWithNewline"?: boolean | null;

    /** Creates a new ConflictRegion instance. */
    constructor($$source: Partial<ConflictRegion> = {}) {
        if (!("index" in $$source)) {
            this["index"] = 0;
        }
        if (!("startLine" in $$source)) {
            this["startLine"] = 0;
        }
        if (!("endLine" in $$source)) {
            this["endLine"] = 0;
        }
        if (!("ours" in $$source)) {
            this["ours"] = [];
        }
        if (!("base" in $$source)) {
            this["base"] = [];
        }
        if (!("theirs" in $$source)) {
            this["theirs"] = [];
        }
        if (!("hasBase" in $$source)) {
            this["hasBase"] = false;
        }
        if (!("oursLabel" in $$source)) {
            this["oursLabel"] = "";
        }
        if (!("theirLabel" in $$source)) {
            this["theirLabel"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConflictRegion instance from a string or object.
     */
    static createFrom($$source: any = {}): ConflictRegion {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ours" in $$parsedSource) {
            $$parsedSource["ours"] = $$createField3_0($$parsedSource["ours"]);
        }
        if ("base" in $$parsedSource) {
            $$parsedSource["base"] = $$createField4_0($$parsedSource["base"]);
        }
        if ("theirs" in $$parsedSource) {
            $$parsedSource["theirs"] = $$createField5_0($$parsedSource["theirs"]);
        }
        return new ConflictRegion($$parsedSource as Partial<ConflictRegion>);
    }
}

/**
 * ConflictSnapshot is the single, atomic read of a conflicted working-tree
 * file: the exact bytes the frontend displays plus the regions parsed from
 * those same bytes. Parsing regions from the same read the UI renders closes
 * the window where an external write between two reads would leave region
 * coordinates pointing at different content. Encoding/LineEndings mirror
 * filesystem.FileContent so the frontend can persist the resolved file without
 * a lossy round-trip.
 */
export class ConflictSnapshot {
    "content": string;
    "encoding": string;
    "lineEndings": string;
    "regions": ConflictRegion[];

    /** Creates a new ConflictSnapshot instance. */
    constructor($$source: Partial<ConflictSnapshot> = {}) {
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("encoding" in $$source)) {
            this["encoding"] = "";
        }
        if (!("lineEndings" in $$source)) {
            this["lineEndings"] = "";
        }
        if (!("regions" in $$source)) {
            this["regions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConflictSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): ConflictSnapshot {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("regions" in $$parsedSource) {
            $$parsedSource["regions"] = $$createField3_0($$parsedSource["regions"]);
        }
        return new ConflictSnapshot($$parsedSource as Partial<ConflictSnapshot>);
    }
}

/**
 * ConflictStages reports which index stages exist for a conflicted path, so the
 * frontend can tell a whole-file side conflict (binary, or delete/modify with a
 * stage absent) from a mergeable text conflict, and offer only the sides that
 * actually exist. Stage 1 is the merge base, 2 is ours (HEAD), 3 is theirs.
 */
export class ConflictStages {
    "path": string;
    "base": StageBlob | null;
    "ours": StageBlob | null;
    "theirs": StageBlob | null;
    "binary": boolean;

    /** Creates a new ConflictStages instance. */
    constructor($$source: Partial<ConflictStages> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("base" in $$source)) {
            this["base"] = null;
        }
        if (!("ours" in $$source)) {
            this["ours"] = null;
        }
        if (!("theirs" in $$source)) {
            this["theirs"] = null;
        }
        if (!("binary" in $$source)) {
            this["binary"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConflictStages instance from a string or object.
     */
    static createFrom($$source: any = {}): ConflictStages {
        const $$createField1_0 = $$createType4;
        const $$createField2_0 = $$createType4;
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("base" in $$parsedSource) {
            $$parsedSource["base"] = $$createField1_0($$parsedSource["base"]);
        }
        if ("ours" in $$parsedSource) {
            $$parsedSource["ours"] = $$createField2_0($$parsedSource["ours"]);
        }
        if ("theirs" in $$parsedSource) {
            $$parsedSource["theirs"] = $$createField3_0($$parsedSource["theirs"]);
        }
        return new ConflictStages($$parsedSource as Partial<ConflictStages>);
    }
}

/**
 * ConflictState is one coherent read of everything a merge-resolution session
 * depends on: which index stages exist, the text snapshot when the conflict is
 * text-mergeable, the operation heads that give Current/Incoming their meaning,
 * and an opaque SourceVersion covering all of it plus the raw working-tree
 * bytes.
 *
 * SourceVersion exists because a filesystem watcher is a hint, not an
 * authority: an event can be missed, coalesced, or arrive late, and a merge
 * session that trusted it would happily overwrite a change it never saw. Every
 * mutation therefore carries the version the user actually reviewed, and the
 * backend re-derives the version inside the same call as the mutation.
 *
 * Snapshot is nil when the stage topology calls for the whole-file side UI (a
 * binary conflict, or a delete/modify where one side has no blob) and when the
 * path is no longer conflicted at all. Heads is nil only when there are no
 * conflict stages, so "resolved outside Firn" can be detected without
 * depending on operation metadata that may already be gone.
 */
export class ConflictState {
    "stages": ConflictStages;
    "snapshot"?: ConflictSnapshot | null;
    "heads"?: MergeHeads | null;
    "sourceVersion": string;

    /** Creates a new ConflictState instance. */
    constructor($$source: Partial<ConflictState> = {}) {
        if (!("stages" in $$source)) {
            this["stages"] = (new ConflictStages());
        }
        if (!("sourceVersion" in $$source)) {
            this["sourceVersion"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConflictState instance from a string or object.
     */
    static createFrom($$source: any = {}): ConflictState {
        const $$createField0_0 = $$createType5;
        const $$createField1_0 = $$createType7;
        const $$createField2_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("stages" in $$parsedSource) {
            $$parsedSource["stages"] = $$createField0_0($$parsedSource["stages"]);
        }
        if ("snapshot" in $$parsedSource) {
            $$parsedSource["snapshot"] = $$createField1_0($$parsedSource["snapshot"]);
        }
        if ("heads" in $$parsedSource) {
            $$parsedSource["heads"] = $$createField2_0($$parsedSource["heads"]);
        }
        return new ConflictState($$parsedSource as Partial<ConflictState>);
    }
}

/**
 * FileChange is one changed path from `git status`. Index and Worktree hold
 * the raw porcelain XY status letters ("M", "A", "D", "R", "?", "."); the
 * frontend owns classification into staged/unstaged/untracked buckets.
 */
export class FileChange {
    "path": string;
    "origPath"?: string;
    "index": string;
    "worktree": string;
    "unmerged"?: boolean;

    /** Creates a new FileChange instance. */
    constructor($$source: Partial<FileChange> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("index" in $$source)) {
            this["index"] = "";
        }
        if (!("worktree" in $$source)) {
            this["worktree"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileChange instance from a string or object.
     */
    static createFrom($$source: any = {}): FileChange {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileChange($$parsedSource as Partial<FileChange>);
    }
}

/**
 * FileContent is file content at a revision, with the states the diff UI must
 * special-case: binary files and files past the diffable size cap ship no
 * content at all — the flags alone drive the UI.
 */
export class FileContent {
    "content": string;
    "binary": boolean;
    "truncated": boolean;

    /** Creates a new FileContent instance. */
    constructor($$source: Partial<FileContent> = {}) {
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("binary" in $$source)) {
            this["binary"] = false;
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileContent instance from a string or object.
     */
    static createFrom($$source: any = {}): FileContent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileContent($$parsedSource as Partial<FileContent>);
    }
}

/**
 * FileHunks is the per-hunk breakdown of a single file's diff. A binary file
 * or a file with no diff yields an empty Hunks slice (never nil, for stable
 * JSON), which the UI renders as "no per-hunk staging here".
 */
export class FileHunks {
    "path": string;
    "hunks": Hunk[];

    /** Creates a new FileHunks instance. */
    constructor($$source: Partial<FileHunks> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("hunks" in $$source)) {
            this["hunks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileHunks instance from a string or object.
     */
    static createFrom($$source: any = {}): FileHunks {
        const $$createField1_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("hunks" in $$parsedSource) {
            $$parsedSource["hunks"] = $$createField1_0($$parsedSource["hunks"]);
        }
        return new FileHunks($$parsedSource as Partial<FileHunks>);
    }
}

/**
 * Hunk is one @@-block of a file's unified diff. Patch is a standalone,
 * applyable patch — the file header followed by this single hunk — so the
 * frontend can replay exactly what the user saw through `git apply` without
 * reconstructing anything. NewStart/NewLines locate the hunk on the new side
 * (the right pane of the diff view) so the UI can anchor a gutter control.
 */
export class Hunk {
    "patch": string;
    "newStart": number;
    "newLines": number;

    /** Creates a new Hunk instance. */
    constructor($$source: Partial<Hunk> = {}) {
        if (!("patch" in $$source)) {
            this["patch"] = "";
        }
        if (!("newStart" in $$source)) {
            this["newStart"] = 0;
        }
        if (!("newLines" in $$source)) {
            this["newLines"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Hunk instance from a string or object.
     */
    static createFrom($$source: any = {}): Hunk {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Hunk($$parsedSource as Partial<Hunk>);
    }
}

/**
 * MergeHead describes one side of an in-progress conflict for the card header.
 * Label is a branch name when resolvable, else the short hash; Hash/Subject
 * come from the commit that side points at.
 */
export class MergeHead {
    "label": string;
    "hash": string;
    "subject": string;

    /** Creates a new MergeHead instance. */
    constructor($$source: Partial<MergeHead> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("hash" in $$source)) {
            this["hash"] = "";
        }
        if (!("subject" in $$source)) {
            this["subject"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MergeHead instance from a string or object.
     */
    static createFrom($$source: any = {}): MergeHead {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MergeHead($$parsedSource as Partial<MergeHead>);
    }
}

/**
 * MergeHeads names both sides of the conflict the user is resolving, plus the
 * operation (merge, rebase, or cherry-pick) so the UI can phrase "incoming"
 * correctly. It reads HEAD (ours) and the operation's incoming ref (theirs).
 */
export class MergeHeads {
    "operation": string;
    "ours": MergeHead;
    "theirs": MergeHead;

    /** Creates a new MergeHeads instance. */
    constructor($$source: Partial<MergeHeads> = {}) {
        if (!("operation" in $$source)) {
            this["operation"] = "";
        }
        if (!("ours" in $$source)) {
            this["ours"] = (new MergeHead());
        }
        if (!("theirs" in $$source)) {
            this["theirs"] = (new MergeHead());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MergeHeads instance from a string or object.
     */
    static createFrom($$source: any = {}): MergeHeads {
        const $$createField1_0 = $$createType12;
        const $$createField2_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ours" in $$parsedSource) {
            $$parsedSource["ours"] = $$createField1_0($$parsedSource["ours"]);
        }
        if ("theirs" in $$parsedSource) {
            $$parsedSource["theirs"] = $$createField2_0($$parsedSource["theirs"]);
        }
        return new MergeHeads($$parsedSource as Partial<MergeHeads>);
    }
}

/**
 * RepoStatus is a snapshot of a repository's state. Paths in Files are
 * relative to RepoRoot (porcelain paths are repo-root-relative even when
 * status runs in a subdirectory, e.g. a workspace inside a monorepo).
 */
export class RepoStatus {
    "isRepo": boolean;
    "repoRoot": string;
    "branch": string;
    "upstream": string;
    "ahead": number;
    "behind": number;
    "files": FileChange[];

    /**
     * Detail explains why a directory that IS a git repo can't be shown
     * (e.g. core.bare=true, no working tree). Empty for a normal repo or a
     * plain non-repo directory. The UI surfaces it instead of a generic
     * "not a git repository" message.
     */
    "detail"?: string;

    /** Creates a new RepoStatus instance. */
    constructor($$source: Partial<RepoStatus> = {}) {
        if (!("isRepo" in $$source)) {
            this["isRepo"] = false;
        }
        if (!("repoRoot" in $$source)) {
            this["repoRoot"] = "";
        }
        if (!("branch" in $$source)) {
            this["branch"] = "";
        }
        if (!("upstream" in $$source)) {
            this["upstream"] = "";
        }
        if (!("ahead" in $$source)) {
            this["ahead"] = 0;
        }
        if (!("behind" in $$source)) {
            this["behind"] = 0;
        }
        if (!("files" in $$source)) {
            this["files"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RepoStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): RepoStatus {
        const $$createField6_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField6_0($$parsedSource["files"]);
        }
        return new RepoStatus($$parsedSource as Partial<RepoStatus>);
    }
}

/**
 * StageBlob is one conflict index entry (a stage-1/2/3 object). Size is the
 * blob byte size and Mode the index mode (e.g. "100644", "100755"), which is
 * part of the conflict's identity: a side that only changed its executable bit
 * still changed. A nil *StageBlob on ConflictStages means the stage is absent
 * — the explicit signal for a delete/modify conflict, never conflated with
 * empty content.
 */
export class StageBlob {
    "hash": string;
    "mode": string;
    "size": number;

    /** Creates a new StageBlob instance. */
    constructor($$source: Partial<StageBlob> = {}) {
        if (!("hash" in $$source)) {
            this["hash"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StageBlob instance from a string or object.
     */
    static createFrom($$source: any = {}): StageBlob {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StageBlob($$parsedSource as Partial<StageBlob>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ConflictRegion.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = StageBlob.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = ConflictStages.createFrom;
const $$createType6 = ConflictSnapshot.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = MergeHeads.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = Hunk.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = MergeHead.createFrom;
const $$createType13 = FileChange.createFrom;
const $$createType14 = $Create.Array($$createType13);
