// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FileContent represents the result of reading a file with metadata.
 */
export class FileContent {
    "content": string;

    /**
     * "utf-8", "utf-8-bom", "utf-16le", "utf-16be", "latin-1"
     */
    "encoding": string;

    /**
     * "lf", "crlf", "cr", "mixed", "none"
     */
    "lineEndings": string;
    "size": number;
    "isBinary": boolean;

    /** Creates a new FileContent instance. */
    constructor($$source: Partial<FileContent> = {}) {
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("encoding" in $$source)) {
            this["encoding"] = "";
        }
        if (!("lineEndings" in $$source)) {
            this["lineEndings"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("isBinary" in $$source)) {
            this["isBinary"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileContent instance from a string or object.
     */
    static createFrom($$source: any = {}): FileContent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileContent($$parsedSource as Partial<FileContent>);
    }
}

/**
 * FileEntry represents a file or directory in the tree.
 * Used by ReadDirectory to return the directory structure.
 */
export class FileEntry {
    "name": string;
    "path": string;
    "isDir": boolean;
    "size": number;
    "modTime": string;
    "children"?: FileEntry[];
    "unreadable"?: boolean;

    /** Creates a new FileEntry instance. */
    constructor($$source: Partial<FileEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("isDir" in $$source)) {
            this["isDir"] = false;
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("modTime" in $$source)) {
            this["modTime"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): FileEntry {
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField5_0($$parsedSource["children"]);
        }
        return new FileEntry($$parsedSource as Partial<FileEntry>);
    }
}

// Private type creation functions
const $$createType0 = FileEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
