// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ActiveRunStatus describes one live run, including background runs whose
 * repository incarnation is no longer current.
 */
export class ActiveRunStatus {
    "identity": RunIdentity;
    "workspaceLabel": string;

    /**
     * running | canceling
     */
    "state": string;

    /** Creates a new ActiveRunStatus instance. */
    constructor($$source: Partial<ActiveRunStatus> = {}) {
        if (!("identity" in $$source)) {
            this["identity"] = (new RunIdentity());
        }
        if (!("workspaceLabel" in $$source)) {
            this["workspaceLabel"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActiveRunStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ActiveRunStatus {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("identity" in $$parsedSource) {
            $$parsedSource["identity"] = $$createField0_0($$parsedSource["identity"]);
        }
        return new ActiveRunStatus($$parsedSource as Partial<ActiveRunStatus>);
    }
}

/**
 * ApplyChallenge is the consent handshake. The token is opaque and single-use;
 * the record behind it holds no document, path, or key. Destinations lists
 * every NEW remote destination the write would open, digest-sorted (spec D8).
 * Present iff the result status is consent_required.
 */
export class ApplyChallenge {
    "token": string;
    "expiresAt": number;
    "destinations": ApplyDestination[];

    /** Creates a new ApplyChallenge instance. */
    constructor($$source: Partial<ApplyChallenge> = {}) {
        if (!("token" in $$source)) {
            this["token"] = "";
        }
        if (!("expiresAt" in $$source)) {
            this["expiresAt"] = 0;
        }
        if (!("destinations" in $$source)) {
            this["destinations"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApplyChallenge instance from a string or object.
     */
    static createFrom($$source: any = {}): ApplyChallenge {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("destinations" in $$parsedSource) {
            $$parsedSource["destinations"] = $$createField2_0($$parsedSource["destinations"]);
        }
        return new ApplyChallenge($$parsedSource as Partial<ApplyChallenge>);
    }
}

/**
 * ApplyDestination is the bounded egress identity shown in the consent
 * prompt — never an API key, never a path. Classification is always "remote"
 * (local destinations never challenge). Provenance names the routing hops
 * that reach it ("agent", "agent (recommendation)"); Model is empty when the
 * hop names a provider and no model.
 */
export class ApplyDestination {
    "provider": string;
    "model": string;
    "endpoint": string;
    "classification": string;
    "provenance": string[];

    /** Creates a new ApplyDestination instance. */
    constructor($$source: Partial<ApplyDestination> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("endpoint" in $$source)) {
            this["endpoint"] = "";
        }
        if (!("classification" in $$source)) {
            this["classification"] = "";
        }
        if (!("provenance" in $$source)) {
            this["provenance"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApplyDestination instance from a string or object.
     */
    static createFrom($$source: any = {}): ApplyDestination {
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("provenance" in $$parsedSource) {
            $$parsedSource["provenance"] = $$createField4_0($$parsedSource["provenance"]);
        }
        return new ApplyDestination($$parsedSource as Partial<ApplyDestination>);
    }
}

/**
 * ApplySource is the closed source union: the applied document, a stored
 * profile at a known revision, or a blank bootstrap.
 */
export class ApplySource {
    "kind": string;
    "profileId"?: string;
    "sourceRevision"?: string;

    /** Creates a new ApplySource instance. */
    constructor($$source: Partial<ApplySource> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApplySource instance from a string or object.
     */
    static createFrom($$source: any = {}): ApplySource {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ApplySource($$parsedSource as Partial<ApplySource>);
    }
}

/**
 * CancelSettingsApplyResult has exactly one success variant; cancel is
 * idempotent, so an absent or expired token is already cancelled.
 */
export class CancelSettingsApplyResult {
    "status": string;

    /** Creates a new CancelSettingsApplyResult instance. */
    constructor($$source: Partial<CancelSettingsApplyResult> = {}) {
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CancelSettingsApplyResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CancelSettingsApplyResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CancelSettingsApplyResult($$parsedSource as Partial<CancelSettingsApplyResult>);
    }
}

/**
 * CapabilityFacts pairs a model's resolved capabilities with the full
 * canonical vocabulary, so the frontend can render both "has" and "could
 * have" without hard-coding the capability list.
 */
export class CapabilityFacts {
    "caps": string[];
    "knownCaps": string[];

    /** Creates a new CapabilityFacts instance. */
    constructor($$source: Partial<CapabilityFacts> = {}) {
        if (!("caps" in $$source)) {
            this["caps"] = [];
        }
        if (!("knownCaps" in $$source)) {
            this["knownCaps"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CapabilityFacts instance from a string or object.
     */
    static createFrom($$source: any = {}): CapabilityFacts {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("caps" in $$parsedSource) {
            $$parsedSource["caps"] = $$createField0_0($$parsedSource["caps"]);
        }
        if ("knownCaps" in $$parsedSource) {
            $$parsedSource["knownCaps"] = $$createField1_0($$parsedSource["knownCaps"]);
        }
        return new CapabilityFacts($$parsedSource as Partial<CapabilityFacts>);
    }
}

/**
 * Change is one staged mutation. Only the members its Kind declares are ever
 * populated: UnmarshalJSON decodes each variant through its own strict struct,
 * so a member borrowed from another variant is an unknown field. Required
 * members are enforced at decode time (that is the only place absence and a
 * typed zero are still distinguishable); validateChange then enforces value
 * rules. The backend never sends a Change to the frontend, so there is no
 * matching MarshalJSON.
 */
export class Change {
    "kind": string;
    "useCase"?: string;
    "role"?: string;
    "name"?: string;
    "endpoint"?: string | null;
    "apiFormat"?: string | null;
    "modelFacts"?: ModelFacts | null;
    "capabilityFacts"?: CapabilityFacts | null;
    "exposedCaps"?: string[];
    "thinkMode"?: string;
    "confirmUnknown"?: boolean;
    "confirmUnknownUseCases"?: string[];
    "confirmDrops"?: string[];

    /** Creates a new Change instance. */
    constructor($$source: Partial<Change> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Change instance from a string or object.
     */
    static createFrom($$source: any = {}): Change {
        const $$createField6_0 = $$createType5;
        const $$createField7_0 = $$createType7;
        const $$createField8_0 = $$createType3;
        const $$createField11_0 = $$createType3;
        const $$createField12_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("modelFacts" in $$parsedSource) {
            $$parsedSource["modelFacts"] = $$createField6_0($$parsedSource["modelFacts"]);
        }
        if ("capabilityFacts" in $$parsedSource) {
            $$parsedSource["capabilityFacts"] = $$createField7_0($$parsedSource["capabilityFacts"]);
        }
        if ("exposedCaps" in $$parsedSource) {
            $$parsedSource["exposedCaps"] = $$createField8_0($$parsedSource["exposedCaps"]);
        }
        if ("confirmUnknownUseCases" in $$parsedSource) {
            $$parsedSource["confirmUnknownUseCases"] = $$createField11_0($$parsedSource["confirmUnknownUseCases"]);
        }
        if ("confirmDrops" in $$parsedSource) {
            $$parsedSource["confirmDrops"] = $$createField12_0($$parsedSource["confirmDrops"]);
        }
        return new Change($$parsedSource as Partial<Change>);
    }
}

/**
 * ChangeDropSet names one staged change and the model-specific fields a real
 * retarget would drop. ChangeID is the §3.3 stable identity (changeStableID).
 */
export class ChangeDropSet {
    "changeId": string;
    "fields": string[];

    /** Creates a new ChangeDropSet instance. */
    constructor($$source: Partial<ChangeDropSet> = {}) {
        if (!("changeId" in $$source)) {
            this["changeId"] = "";
        }
        if (!("fields" in $$source)) {
            this["fields"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChangeDropSet instance from a string or object.
     */
    static createFrom($$source: any = {}): ChangeDropSet {
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fields" in $$parsedSource) {
            $$parsedSource["fields"] = $$createField1_0($$parsedSource["fields"]);
        }
        return new ChangeDropSet($$parsedSource as Partial<ChangeDropSet>);
    }
}

/**
 * ConfirmSettingsApplyRequest is Call 2. Call 1 retained no request, so the
 * frontend resends the whole thing alongside the opaque challenge token.
 */
export class ConfirmSettingsApplyRequest {
    "challengeToken": string;
    "request": SettingsApplyRequest;

    /** Creates a new ConfirmSettingsApplyRequest instance. */
    constructor($$source: Partial<ConfirmSettingsApplyRequest> = {}) {
        if (!("challengeToken" in $$source)) {
            this["challengeToken"] = "";
        }
        if (!("request" in $$source)) {
            this["request"] = (new SettingsApplyRequest());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfirmSettingsApplyRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ConfirmSettingsApplyRequest {
        const $$createField1_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("request" in $$parsedSource) {
            $$parsedSource["request"] = $$createField1_0($$parsedSource["request"]);
        }
        return new ConfirmSettingsApplyRequest($$parsedSource as Partial<ConfirmSettingsApplyRequest>);
    }
}

/**
 * ConsentChallenge is one pending Remote-egress consent decision, bound to the
 * full run identity and the exact destination it would authorize.
 */
export class ConsentChallenge {
    "id": string;
    "identity": RunIdentity;
    "destination": ProviderDestination;
    "destinationDigest": string;

    /**
     * Unix milliseconds
     */
    "expiresAt": number;

    /** Creates a new ConsentChallenge instance. */
    constructor($$source: Partial<ConsentChallenge> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("identity" in $$source)) {
            this["identity"] = (new RunIdentity());
        }
        if (!("destination" in $$source)) {
            this["destination"] = (new ProviderDestination());
        }
        if (!("destinationDigest" in $$source)) {
            this["destinationDigest"] = "";
        }
        if (!("expiresAt" in $$source)) {
            this["expiresAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConsentChallenge instance from a string or object.
     */
    static createFrom($$source: any = {}): ConsentChallenge {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("identity" in $$parsedSource) {
            $$parsedSource["identity"] = $$createField1_0($$parsedSource["identity"]);
        }
        if ("destination" in $$parsedSource) {
            $$parsedSource["destination"] = $$createField2_0($$parsedSource["destination"]);
        }
        return new ConsentChallenge($$parsedSource as Partial<ConsentChallenge>);
    }
}

/**
 * ContextReceipt summarizes what context was attached to an admitted turn.
 */
export class ContextReceipt {
    "included": number;
    "bytes": number;
    "excluded": number;

    /** Creates a new ContextReceipt instance. */
    constructor($$source: Partial<ContextReceipt> = {}) {
        if (!("included" in $$source)) {
            this["included"] = 0;
        }
        if (!("bytes" in $$source)) {
            this["bytes"] = 0;
        }
        if (!("excluded" in $$source)) {
            this["excluded"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContextReceipt instance from a string or object.
     */
    static createFrom($$source: any = {}): ContextReceipt {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ContextReceipt($$parsedSource as Partial<ContextReceipt>);
    }
}

/**
 * ConversationIdentity names one conversation within a bound repository.
 */
export class ConversationIdentity {
    "repoEpoch": number;
    "workspaceId": string;
    "conversationId": string;

    /** Creates a new ConversationIdentity instance. */
    constructor($$source: Partial<ConversationIdentity> = {}) {
        if (!("repoEpoch" in $$source)) {
            this["repoEpoch"] = 0;
        }
        if (!("workspaceId" in $$source)) {
            this["workspaceId"] = "";
        }
        if (!("conversationId" in $$source)) {
            this["conversationId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConversationIdentity instance from a string or object.
     */
    static createFrom($$source: any = {}): ConversationIdentity {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConversationIdentity($$parsedSource as Partial<ConversationIdentity>);
    }
}

/**
 * DestinationGrantsResult is the closed result of the grant-only approval
 * flow (spec D13). It approves destinations and authorizes NO document write,
 * so it carries no projection, no diagnostics, and no conflict kind: the
 * status alone says what happened.
 * 
 * 	none             nothing to approve — no configuration, or every remote
 * 	                 the agent route reaches is already granted
 * 	consent_required the challenge below lists what would be opened
 * 	granted          the whole approved batch is durably recorded
 * 	uncertain        the batch write failed; see ConsentStore.GrantMany
 * 	conflict         the token is unknown, expired, cancelled, issued by the
 * 	                 settings-write flow, or no longer describes the ACTIVE
 * 	                 configuration
 * 	busy             a turn is running; nothing was consumed, retry the token
 * 	unavailable      consent storage cannot authorize or record anything
 * 	config_invalid   the active configuration could not be loaded
 * 
 * Challenge is present iff Status is consent_required.
 */
export class DestinationGrantsResult {
    "status": string;
    "challenge"?: ApplyChallenge | null;

    /** Creates a new DestinationGrantsResult instance. */
    constructor($$source: Partial<DestinationGrantsResult> = {}) {
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DestinationGrantsResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DestinationGrantsResult {
        const $$createField1_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("challenge" in $$parsedSource) {
            $$parsedSource["challenge"] = $$createField1_0($$parsedSource["challenge"]);
        }
        return new DestinationGrantsResult($$parsedSource as Partial<DestinationGrantsResult>);
    }
}

/**
 * Diagnostic is one allowlisted configuration finding. SubjectName is a
 * length-bounded role/model/provider/use_case name; never a path or value.
 */
export class Diagnostic {
    "code": string;

    /**
     * "" | role | model | provider | use_case
     */
    "subjectKind": string;
    "subjectName": string;
    "blocking": boolean;

    /** Creates a new Diagnostic instance. */
    constructor($$source: Partial<Diagnostic> = {}) {
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("subjectKind" in $$source)) {
            this["subjectKind"] = "";
        }
        if (!("subjectName" in $$source)) {
            this["subjectName"] = "";
        }
        if (!("blocking" in $$source)) {
            this["blocking"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Diagnostic instance from a string or object.
     */
    static createFrom($$source: any = {}): Diagnostic {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Diagnostic($$parsedSource as Partial<Diagnostic>);
    }
}

/**
 * GolemProfileListResult is the closed §5.6 list union. `limited` carries the
 * first maxProjectionEntries rows in stable ID order.
 */
export class GolemProfileListResult {
    "status": string;

    /**
     * Profiles MUST be non-empty whenever Status is "loaded" or "limited". That
     * is guaranteed, not merely hoped for: the embedded curated catalog always
     * contributes at least "curated/local" to Store.List, so an empty
     * loaded/limited result is unreachable by construction, and Task 3's
     * TestListGolemProfilesNeverEmpty is the guard that pins it. `omitempty`
     * here is deliberate and depends on that invariant holding — marshaling a
     * genuinely EMPTY slice would silently drop the member and produce
     * {"status":"loaded"}, which is exactly the byte shape the shared corpus
     * records as reject (reject-profile-list-missing-profiles.json), not the
     * accept shape {"status":"loaded","profiles":[]}
     * (accept-profile-list-loaded-empty.json — that fixture documents a wire
     * shape the SCHEMA allows, not one this producer ever emits). Do not "fix"
     * this by dropping omitempty or switching to *[]ProfileInfo — see
     * TestGolemProfileResultsRoundTripTheContract in settings_apply_test.go,
     * which proves every result this producer can actually emit round-trips
     * through the same contract checks a fixture takes.
     */
    "profiles"?: ProfileInfo[];
    "diagnostics"?: ProfileDiagnostic[];

    /** Creates a new GolemProfileListResult instance. */
    constructor($$source: Partial<GolemProfileListResult> = {}) {
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GolemProfileListResult instance from a string or object.
     */
    static createFrom($$source: any = {}): GolemProfileListResult {
        const $$createField1_0 = $$createType13;
        const $$createField2_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("profiles" in $$parsedSource) {
            $$parsedSource["profiles"] = $$createField1_0($$parsedSource["profiles"]);
        }
        if ("diagnostics" in $$parsedSource) {
            $$parsedSource["diagnostics"] = $$createField2_0($$parsedSource["diagnostics"]);
        }
        return new GolemProfileListResult($$parsedSource as Partial<GolemProfileListResult>);
    }
}

/**
 * GolemProfileLoadResult carries a draft preview plus the provenance the
 * frontend needs to stage a profile-source Apply.
 */
export class GolemProfileLoadResult {
    "status": string;
    "profileId"?: string;
    "sourceRevision"?: string;
    "projection"?: ProfileDraftProjection | null;
    "diagnostics"?: ProfileDiagnostic[];

    /** Creates a new GolemProfileLoadResult instance. */
    constructor($$source: Partial<GolemProfileLoadResult> = {}) {
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GolemProfileLoadResult instance from a string or object.
     */
    static createFrom($$source: any = {}): GolemProfileLoadResult {
        const $$createField3_0 = $$createType17;
        const $$createField4_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("projection" in $$parsedSource) {
            $$parsedSource["projection"] = $$createField3_0($$parsedSource["projection"]);
        }
        if ("diagnostics" in $$parsedSource) {
            $$parsedSource["diagnostics"] = $$createField4_0($$parsedSource["diagnostics"]);
        }
        return new GolemProfileLoadResult($$parsedSource as Partial<GolemProfileLoadResult>);
    }
}

/**
 * GolemProfileSaveResult is the closed §5.6 save union. The two CAS failures
 * are distinct conflict kinds: active_revision (the applied configuration
 * moved under the caller) and profile_target (the destination profile moved
 * or appeared). The durability warning rides the SAVED variant — upstream
 * reports it with a nil error, never as a failure.
 */
export class GolemProfileSaveResult {
    "status": string;
    "profile"?: SavedProfile | null;
    "warning"?: string;
    "conflict"?: string;
    "diagnostics"?: ProfileDiagnostic[];

    /** Creates a new GolemProfileSaveResult instance. */
    constructor($$source: Partial<GolemProfileSaveResult> = {}) {
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GolemProfileSaveResult instance from a string or object.
     */
    static createFrom($$source: any = {}): GolemProfileSaveResult {
        const $$createField1_0 = $$createType19;
        const $$createField4_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("profile" in $$parsedSource) {
            $$parsedSource["profile"] = $$createField1_0($$parsedSource["profile"]);
        }
        if ("diagnostics" in $$parsedSource) {
            $$parsedSource["diagnostics"] = $$createField4_0($$parsedSource["diagnostics"]);
        }
        return new GolemProfileSaveResult($$parsedSource as Partial<GolemProfileSaveResult>);
    }
}

/**
 * ModelFacts is a route change's complete model description. The optional
 * members are nil exactly when the caller omitted them; upstream reads a nil
 * numeric fact as zero.
 */
export class ModelFacts {
    "provider": string;
    "model": string;
    "type": string;
    "parameters"?: string | null;
    "contextWindow"?: number | null;
    "dimensions"?: number | null;

    /** Creates a new ModelFacts instance. */
    constructor($$source: Partial<ModelFacts> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelFacts instance from a string or object.
     */
    static createFrom($$source: any = {}): ModelFacts {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelFacts($$parsedSource as Partial<ModelFacts>);
    }
}

/**
 * ModelProjection is one models-map entry. Role is the map key (a role name);
 * ModelName is the provider's model ID — different namespaces, both shown.
 * EffectiveCapabilities/CapabilityFacts.Caps are this model's own canonical
 * ResolvedCapabilities(); ExposedCapabilities is what a selector-sharing
 * mutation would actually apply (selectorCapabilityOverrides). RoutedUseCases
 * lists every use case reaching this role (directly or through a fallback
 * chain); Removable is true when nothing references it.
 * 
 * HasThinkTags/HasSlots are EXISTENCE facts only: a real model retarget drops
 * these authored, model-specific members, so the editor has to disclose the
 * loss before staging. The values themselves never cross the boundary.
 */
export class ModelProjection {
    "role": string;
    "modelName": string;
    "provider": string;
    "type": string;
    "parameters"?: string;
    "contextWindow"?: number;
    "dimensions"?: number;
    "effectiveCapabilities": string[];
    "capabilityFacts": CapabilityFacts;
    "exposedCapabilities": string[];
    "thinkMode": string;
    "routedUseCases": string[];
    "hasThinkTags": boolean;
    "hasSlots": boolean;
    "removable": boolean;

    /** Creates a new ModelProjection instance. */
    constructor($$source: Partial<ModelProjection> = {}) {
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("modelName" in $$source)) {
            this["modelName"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("effectiveCapabilities" in $$source)) {
            this["effectiveCapabilities"] = [];
        }
        if (!("capabilityFacts" in $$source)) {
            this["capabilityFacts"] = (new CapabilityFacts());
        }
        if (!("exposedCapabilities" in $$source)) {
            this["exposedCapabilities"] = [];
        }
        if (!("thinkMode" in $$source)) {
            this["thinkMode"] = "";
        }
        if (!("routedUseCases" in $$source)) {
            this["routedUseCases"] = [];
        }
        if (!("hasThinkTags" in $$source)) {
            this["hasThinkTags"] = false;
        }
        if (!("hasSlots" in $$source)) {
            this["hasSlots"] = false;
        }
        if (!("removable" in $$source)) {
            this["removable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelProjection instance from a string or object.
     */
    static createFrom($$source: any = {}): ModelProjection {
        const $$createField7_0 = $$createType3;
        const $$createField8_0 = $$createType6;
        const $$createField9_0 = $$createType3;
        const $$createField11_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("effectiveCapabilities" in $$parsedSource) {
            $$parsedSource["effectiveCapabilities"] = $$createField7_0($$parsedSource["effectiveCapabilities"]);
        }
        if ("capabilityFacts" in $$parsedSource) {
            $$parsedSource["capabilityFacts"] = $$createField8_0($$parsedSource["capabilityFacts"]);
        }
        if ("exposedCapabilities" in $$parsedSource) {
            $$parsedSource["exposedCapabilities"] = $$createField9_0($$parsedSource["exposedCapabilities"]);
        }
        if ("routedUseCases" in $$parsedSource) {
            $$parsedSource["routedUseCases"] = $$createField11_0($$parsedSource["routedUseCases"]);
        }
        return new ModelProjection($$parsedSource as Partial<ModelProjection>);
    }
}

/**
 * ProfileDiagnostic is the closed profile-store finding. Paths never cross.
 */
export class ProfileDiagnostic {
    "code": string;
    "profileId"?: string;

    /** Creates a new ProfileDiagnostic instance. */
    constructor($$source: Partial<ProfileDiagnostic> = {}) {
        if (!("code" in $$source)) {
            this["code"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileDiagnostic instance from a string or object.
     */
    static createFrom($$source: any = {}): ProfileDiagnostic {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProfileDiagnostic($$parsedSource as Partial<ProfileDiagnostic>);
    }
}

/**
 * ProfileDraftProjection is a profile preview: the settings projection minus
 * sourceOrigin and revision, always credential-free.
 */
export class ProfileDraftProjection {
    "state": string;
    "readOnly": boolean;
    "editable": boolean;
    "routes": RouteProjection[];
    "models": ModelProjection[];
    "providers": ProviderProjection[];
    "diagnostics": Diagnostic[];

    /** Creates a new ProfileDraftProjection instance. */
    constructor($$source: Partial<ProfileDraftProjection> = {}) {
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("readOnly" in $$source)) {
            this["readOnly"] = false;
        }
        if (!("editable" in $$source)) {
            this["editable"] = false;
        }
        if (!("routes" in $$source)) {
            this["routes"] = [];
        }
        if (!("models" in $$source)) {
            this["models"] = [];
        }
        if (!("providers" in $$source)) {
            this["providers"] = [];
        }
        if (!("diagnostics" in $$source)) {
            this["diagnostics"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileDraftProjection instance from a string or object.
     */
    static createFrom($$source: any = {}): ProfileDraftProjection {
        const $$createField3_0 = $$createType21;
        const $$createField4_0 = $$createType23;
        const $$createField5_0 = $$createType25;
        const $$createField6_0 = $$createType27;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("routes" in $$parsedSource) {
            $$parsedSource["routes"] = $$createField3_0($$parsedSource["routes"]);
        }
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField4_0($$parsedSource["models"]);
        }
        if ("providers" in $$parsedSource) {
            $$parsedSource["providers"] = $$createField5_0($$parsedSource["providers"]);
        }
        if ("diagnostics" in $$parsedSource) {
            $$parsedSource["diagnostics"] = $$createField6_0($$parsedSource["diagnostics"]);
        }
        return new ProfileDraftProjection($$parsedSource as Partial<ProfileDraftProjection>);
    }
}

/**
 * ProfileInfo is one §5.6 list row. Store.List user rows carry ID only —
 * description and revision stay absent until Load supplies them, never
 * invented (§5.3). Curated is derived from the namespace by the producer, so
 * the flag can never disagree with the id.
 */
export class ProfileInfo {
    "id": string;
    "description"?: string;
    "curated": boolean;
    "revision"?: string;

    /** Creates a new ProfileInfo instance. */
    constructor($$source: Partial<ProfileInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("curated" in $$source)) {
            this["curated"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ProfileInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProfileInfo($$parsedSource as Partial<ProfileInfo>);
    }
}

/**
 * ProviderDestination identifies where agent traffic would go. It is safe to
 * cross the Wails boundary: no API key, no filesystem paths.
 */
export class ProviderDestination {
    "provider": string;
    "model": string;
    "endpoint": string;

    /**
     * local | remote
     */
    "classification": string;
    "digest": string;

    /** Creates a new ProviderDestination instance. */
    constructor($$source: Partial<ProviderDestination> = {}) {
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("endpoint" in $$source)) {
            this["endpoint"] = "";
        }
        if (!("classification" in $$source)) {
            this["classification"] = "";
        }
        if (!("digest" in $$source)) {
            this["digest"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderDestination instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderDestination {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProviderDestination($$parsedSource as Partial<ProviderDestination>);
    }
}

/**
 * ProviderProjection is one provider. Endpoint is the NormalizeEndpoint
 * canonical form, "" when not derivable (Classification then "unknown").
 * CredentialState is presence, not a usability promise. reference_unavailable
 * is not producible by the current loader (an unresolved ${ENV} key
 * reference hard-fails the whole document load, so no provider ever reaches
 * this projection with a dangling reference); it is retained because the
 * spec closes the enum.
 */
export class ProviderProjection {
    "name": string;
    "endpoint": string;

    /**
     * local | remote | unknown
     */
    "classification": string;
    "apiFormat": string;

    /**
     * none | available | reference_unavailable
     */
    "credentialState": string;

    /** Creates a new ProviderProjection instance. */
    constructor($$source: Partial<ProviderProjection> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("endpoint" in $$source)) {
            this["endpoint"] = "";
        }
        if (!("classification" in $$source)) {
            this["classification"] = "";
        }
        if (!("apiFormat" in $$source)) {
            this["apiFormat"] = "";
        }
        if (!("credentialState" in $$source)) {
            this["credentialState"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderProjection instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderProjection {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProviderProjection($$parsedSource as Partial<ProviderProjection>);
    }
}

/**
 * RouteProjection is one defaults.* entry: use case -> model role.
 */
export class RouteProjection {
    "useCase": string;
    "role": string;

    /** Creates a new RouteProjection instance. */
    constructor($$source: Partial<RouteProjection> = {}) {
        if (!("useCase" in $$source)) {
            this["useCase"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RouteProjection instance from a string or object.
     */
    static createFrom($$source: any = {}): RouteProjection {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RouteProjection($$parsedSource as Partial<RouteProjection>);
    }
}

/**
 * RunIdentity names one run within a conversation.
 */
export class RunIdentity {
    "repoEpoch": number;
    "workspaceId": string;
    "conversationId": string;
    "runId": string;

    /** Creates a new RunIdentity instance. */
    constructor($$source: Partial<RunIdentity> = {}) {
        if (!("repoEpoch" in $$source)) {
            this["repoEpoch"] = 0;
        }
        if (!("workspaceId" in $$source)) {
            this["workspaceId"] = "";
        }
        if (!("conversationId" in $$source)) {
            this["conversationId"] = "";
        }
        if (!("runId" in $$source)) {
            this["runId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunIdentity instance from a string or object.
     */
    static createFrom($$source: any = {}): RunIdentity {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RunIdentity($$parsedSource as Partial<RunIdentity>);
    }
}

/**
 * SaveGolemProfileAsRequest is the §5.6 save request. ExpectedRevision is nil
 * exactly when the caller omitted it: absent means create-only and present
 * means compare-and-replace — there is no empty-string sentinel and no
 * overwrite boolean (§5.3), which is why the member is presence-preserving.
 */
export class SaveGolemProfileAsRequest {
    "id": string;
    "expectedRevision"?: string | null;
    "appliedRevision": string;

    /** Creates a new SaveGolemProfileAsRequest instance. */
    constructor($$source: Partial<SaveGolemProfileAsRequest> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("appliedRevision" in $$source)) {
            this["appliedRevision"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveGolemProfileAsRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveGolemProfileAsRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SaveGolemProfileAsRequest($$parsedSource as Partial<SaveGolemProfileAsRequest>);
    }
}

/**
 * SavedProfile is the saved outcome's identity: the user profile id and the
 * revision the store reports for the written bytes.
 */
export class SavedProfile {
    "id": string;
    "revision": string;

    /** Creates a new SavedProfile instance. */
    constructor($$source: Partial<SavedProfile> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("revision" in $$source)) {
            this["revision"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SavedProfile instance from a string or object.
     */
    static createFrom($$source: any = {}): SavedProfile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SavedProfile($$parsedSource as Partial<SavedProfile>);
    }
}

/**
 * SettingsApplyRequest is the complete staged write. TargetRevision is nil
 * exactly when the caller omitted it (Create); Changes and Keys are non-null
 * collections.
 */
export class SettingsApplyRequest {
    "targetRevision"?: string | null;
    "source": ApplySource;
    "changes": Change[];
    "keys": { [_ in string]?: string };

    /** Creates a new SettingsApplyRequest instance. */
    constructor($$source: Partial<SettingsApplyRequest> = {}) {
        if (!("source" in $$source)) {
            this["source"] = (new ApplySource());
        }
        if (!("changes" in $$source)) {
            this["changes"] = [];
        }
        if (!("keys" in $$source)) {
            this["keys"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsApplyRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SettingsApplyRequest {
        const $$createField1_0 = $$createType28;
        const $$createField2_0 = $$createType30;
        const $$createField3_0 = $$createType31;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("source" in $$parsedSource) {
            $$parsedSource["source"] = $$createField1_0($$parsedSource["source"]);
        }
        if ("changes" in $$parsedSource) {
            $$parsedSource["changes"] = $$createField2_0($$parsedSource["changes"]);
        }
        if ("keys" in $$parsedSource) {
            $$parsedSource["keys"] = $$createField3_0($$parsedSource["keys"]);
        }
        return new SettingsApplyRequest($$parsedSource as Partial<SettingsApplyRequest>);
    }
}

/**
 * SettingsApplyResult is the closed apply/create/confirm outcome.
 */
export class SettingsApplyResult {
    "status": string;
    "projection"?: SettingsProjection | null;
    "warning"?: string;
    "challenge"?: ApplyChallenge | null;
    "drops"?: ChangeDropSet[];
    "conflict"?: string;
    "consentOutcome"?: string;
    "diagnostics"?: Diagnostic[];

    /** Creates a new SettingsApplyResult instance. */
    constructor($$source: Partial<SettingsApplyResult> = {}) {
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsApplyResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SettingsApplyResult {
        const $$createField1_0 = $$createType33;
        const $$createField3_0 = $$createType11;
        const $$createField4_0 = $$createType35;
        const $$createField7_0 = $$createType27;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("projection" in $$parsedSource) {
            $$parsedSource["projection"] = $$createField1_0($$parsedSource["projection"]);
        }
        if ("challenge" in $$parsedSource) {
            $$parsedSource["challenge"] = $$createField3_0($$parsedSource["challenge"]);
        }
        if ("drops" in $$parsedSource) {
            $$parsedSource["drops"] = $$createField4_0($$parsedSource["drops"]);
        }
        if ("diagnostics" in $$parsedSource) {
            $$parsedSource["diagnostics"] = $$createField7_0($$parsedSource["diagnostics"]);
        }
        return new SettingsApplyResult($$parsedSource as Partial<SettingsApplyResult>);
    }
}

/**
 * SettingsProjection is the Wails-facing read-only view of the effective Golem
 * configuration. It never carries filesystem paths, raw JSON, API keys,
 * environment variable names, or raw go-llm error text. Revision is present
 * only for Ready/Limited (a loaded document); ReadOnly is the go-llm document
 * fact, Editable is the Firn identity-safety fact — they can diverge (a
 * duplicate-only document is ReadOnly but still Editable).
 */
export class SettingsProjection {
    /**
     * missing | invalid | limited | ready
     */
    "state": string;

    /**
     * none | env | working_directory | user_config | legacy
     */
    "sourceOrigin": string;
    "revision"?: string;
    "readOnly": boolean;
    "editable": boolean;
    "routes": RouteProjection[];
    "models": ModelProjection[];
    "providers": ProviderProjection[];
    "diagnostics": Diagnostic[];

    /** Creates a new SettingsProjection instance. */
    constructor($$source: Partial<SettingsProjection> = {}) {
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("sourceOrigin" in $$source)) {
            this["sourceOrigin"] = "";
        }
        if (!("readOnly" in $$source)) {
            this["readOnly"] = false;
        }
        if (!("editable" in $$source)) {
            this["editable"] = false;
        }
        if (!("routes" in $$source)) {
            this["routes"] = [];
        }
        if (!("models" in $$source)) {
            this["models"] = [];
        }
        if (!("providers" in $$source)) {
            this["providers"] = [];
        }
        if (!("diagnostics" in $$source)) {
            this["diagnostics"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsProjection instance from a string or object.
     */
    static createFrom($$source: any = {}): SettingsProjection {
        const $$createField5_0 = $$createType21;
        const $$createField6_0 = $$createType23;
        const $$createField7_0 = $$createType25;
        const $$createField8_0 = $$createType27;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("routes" in $$parsedSource) {
            $$parsedSource["routes"] = $$createField5_0($$parsedSource["routes"]);
        }
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField6_0($$parsedSource["models"]);
        }
        if ("providers" in $$parsedSource) {
            $$parsedSource["providers"] = $$createField7_0($$parsedSource["providers"]);
        }
        if ("diagnostics" in $$parsedSource) {
            $$parsedSource["diagnostics"] = $$createField8_0($$parsedSource["diagnostics"]);
        }
        return new SettingsProjection($$parsedSource as Partial<SettingsProjection>);
    }
}

/**
 * SettingsReloadResult is the Wails-facing reload outcome. Busy means the
 * idle barrier rejected the reload and Projection is the unchanged current
 * snapshot's.
 */
export class SettingsReloadResult {
    "busy": boolean;
    "projection": SettingsProjection;

    /** Creates a new SettingsReloadResult instance. */
    constructor($$source: Partial<SettingsReloadResult> = {}) {
        if (!("busy" in $$source)) {
            this["busy"] = false;
        }
        if (!("projection" in $$source)) {
            this["projection"] = (new SettingsProjection());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsReloadResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SettingsReloadResult {
        const $$createField1_0 = $$createType32;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("projection" in $$parsedSource) {
            $$parsedSource["projection"] = $$createField1_0($$parsedSource["projection"]);
        }
        return new SettingsReloadResult($$parsedSource as Partial<SettingsReloadResult>);
    }
}

/**
 * Status is the Wails-facing Golem status snapshot. It never carries
 * filesystem roots or paths; InitError and Warnings are fixed messages only.
 */
export class Status {
    "available": boolean;
    "workspaceLabel": string;
    "identity": ConversationIdentity;
    "destination"?: ProviderDestination | null;
    "needsConsent": boolean;
    "consentChallenge"?: ConsentChallenge | null;
    "activeRuns": ActiveRunStatus[];
    "warnings"?: string[];
    "initError"?: string;

    /** Creates a new Status instance. */
    constructor($$source: Partial<Status> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("workspaceLabel" in $$source)) {
            this["workspaceLabel"] = "";
        }
        if (!("identity" in $$source)) {
            this["identity"] = (new ConversationIdentity());
        }
        if (!("needsConsent" in $$source)) {
            this["needsConsent"] = false;
        }
        if (!("activeRuns" in $$source)) {
            this["activeRuns"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     */
    static createFrom($$source: any = {}): Status {
        const $$createField2_0 = $$createType36;
        const $$createField3_0 = $$createType37;
        const $$createField5_0 = $$createType39;
        const $$createField6_0 = $$createType41;
        const $$createField7_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("identity" in $$parsedSource) {
            $$parsedSource["identity"] = $$createField2_0($$parsedSource["identity"]);
        }
        if ("destination" in $$parsedSource) {
            $$parsedSource["destination"] = $$createField3_0($$parsedSource["destination"]);
        }
        if ("consentChallenge" in $$parsedSource) {
            $$parsedSource["consentChallenge"] = $$createField5_0($$parsedSource["consentChallenge"]);
        }
        if ("activeRuns" in $$parsedSource) {
            $$parsedSource["activeRuns"] = $$createField6_0($$parsedSource["activeRuns"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField7_0($$parsedSource["warnings"]);
        }
        return new Status($$parsedSource as Partial<Status>);
    }
}

/**
 * StatusRequest asks for the Golem status of one workspace under the caller's
 * believed repository epoch.
 */
export class StatusRequest {
    "repoEpoch": number;
    "workspaceId": string;

    /** Creates a new StatusRequest instance. */
    constructor($$source: Partial<StatusRequest> = {}) {
        if (!("repoEpoch" in $$source)) {
            this["repoEpoch"] = 0;
        }
        if (!("workspaceId" in $$source)) {
            this["workspaceId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatusRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): StatusRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StatusRequest($$parsedSource as Partial<StatusRequest>);
    }
}

/**
 * TurnAdmission is the synchronous result of StartTurn.
 */
export class TurnAdmission {
    /**
     * accepted | needs_consent
     */
    "state": string;
    "identity": RunIdentity;
    "destination": ProviderDestination;
    "context": ContextReceipt;
    "consentChallenge"?: ConsentChallenge | null;

    /** Creates a new TurnAdmission instance. */
    constructor($$source: Partial<TurnAdmission> = {}) {
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("identity" in $$source)) {
            this["identity"] = (new RunIdentity());
        }
        if (!("destination" in $$source)) {
            this["destination"] = (new ProviderDestination());
        }
        if (!("context" in $$source)) {
            this["context"] = (new ContextReceipt());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TurnAdmission instance from a string or object.
     */
    static createFrom($$source: any = {}): TurnAdmission {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType9;
        const $$createField3_0 = $$createType42;
        const $$createField4_0 = $$createType39;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("identity" in $$parsedSource) {
            $$parsedSource["identity"] = $$createField1_0($$parsedSource["identity"]);
        }
        if ("destination" in $$parsedSource) {
            $$parsedSource["destination"] = $$createField2_0($$parsedSource["destination"]);
        }
        if ("context" in $$parsedSource) {
            $$parsedSource["context"] = $$createField3_0($$parsedSource["context"]);
        }
        if ("consentChallenge" in $$parsedSource) {
            $$parsedSource["consentChallenge"] = $$createField4_0($$parsedSource["consentChallenge"]);
        }
        return new TurnAdmission($$parsedSource as Partial<TurnAdmission>);
    }
}

/**
 * TurnRequest submits one turn for admission. ConsentChallengeID is set only
 * on the exact retry of a previously issued consent challenge.
 */
export class TurnRequest {
    "identity": RunIdentity;
    "message": string;
    "contextRefs": string[];
    "consentChallengeId"?: string;

    /** Creates a new TurnRequest instance. */
    constructor($$source: Partial<TurnRequest> = {}) {
        if (!("identity" in $$source)) {
            this["identity"] = (new RunIdentity());
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("contextRefs" in $$source)) {
            this["contextRefs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TurnRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): TurnRequest {
        const $$createField0_0 = $$createType0;
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("identity" in $$parsedSource) {
            $$parsedSource["identity"] = $$createField0_0($$parsedSource["identity"]);
        }
        if ("contextRefs" in $$parsedSource) {
            $$parsedSource["contextRefs"] = $$createField2_0($$parsedSource["contextRefs"]);
        }
        return new TurnRequest($$parsedSource as Partial<TurnRequest>);
    }
}

// Private type creation functions
const $$createType0 = RunIdentity.createFrom;
const $$createType1 = ApplyDestination.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = ModelFacts.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = CapabilityFacts.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = SettingsApplyRequest.createFrom;
const $$createType9 = ProviderDestination.createFrom;
const $$createType10 = ApplyChallenge.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = ProfileInfo.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = ProfileDiagnostic.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = ProfileDraftProjection.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = SavedProfile.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = RouteProjection.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = ModelProjection.createFrom;
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = ProviderProjection.createFrom;
const $$createType25 = $Create.Array($$createType24);
const $$createType26 = Diagnostic.createFrom;
const $$createType27 = $Create.Array($$createType26);
const $$createType28 = ApplySource.createFrom;
const $$createType29 = Change.createFrom;
const $$createType30 = $Create.Array($$createType29);
const $$createType31 = $Create.Map($Create.Any, $Create.Any);
const $$createType32 = SettingsProjection.createFrom;
const $$createType33 = $Create.Nullable($$createType32);
const $$createType34 = ChangeDropSet.createFrom;
const $$createType35 = $Create.Array($$createType34);
const $$createType36 = ConversationIdentity.createFrom;
const $$createType37 = $Create.Nullable($$createType9);
const $$createType38 = ConsentChallenge.createFrom;
const $$createType39 = $Create.Nullable($$createType38);
const $$createType40 = ActiveRunStatus.createFrom;
const $$createType41 = $Create.Array($$createType40);
const $$createType42 = ContextReceipt.createFrom;
