// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class OutputEntry {
    "stream": string;
    "text": string;
    "timestamp": number;

    /** Creates a new OutputEntry instance. */
    constructor($$source: Partial<OutputEntry> = {}) {
        if (!("stream" in $$source)) {
            this["stream"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OutputEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): OutputEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OutputEntry($$parsedSource as Partial<OutputEntry>);
    }
}

export class Record {
    "version": number;
    "historyId": string;
    "kind": RecordKind;
    "profileId": string;
    "profileName": string;
    "state": string;
    "exitCode": number;
    "startedAt": number;
    "completedAt": number;
    "outputAvailable": boolean;

    /**
     * Truncated marks a record whose saved output is a prefix of what the run
     * actually produced. It rides on the summary (not just the record) so the
     * index carries it and the UI can warn before loading, which matters most for
     * Diff: comparing a truncated run against a complete one invents differences.
     */
    "truncated"?: boolean;
    "workingDir"?: string;
    "entries"?: OutputEntry[];

    /** Creates a new Record instance. */
    constructor($$source: Partial<Record> = {}) {
        if (!("version" in $$source)) {
            this["version"] = 0;
        }
        if (!("historyId" in $$source)) {
            this["historyId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = RecordKind.$zero;
        }
        if (!("profileId" in $$source)) {
            this["profileId"] = "";
        }
        if (!("profileName" in $$source)) {
            this["profileName"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("exitCode" in $$source)) {
            this["exitCode"] = 0;
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = 0;
        }
        if (!("completedAt" in $$source)) {
            this["completedAt"] = 0;
        }
        if (!("outputAvailable" in $$source)) {
            this["outputAvailable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Record instance from a string or object.
     */
    static createFrom($$source: any = {}): Record {
        const $$createField12_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField12_0($$parsedSource["entries"]);
        }
        return new Record($$parsedSource as Partial<Record>);
    }
}

export class RecordInput {
    "kind": RecordKind;
    "profileId": string;
    "profileName": string;
    "state": string;
    "exitCode": number;
    "startedAt": number;
    "completedAt": number;
    "workspaceEpoch"?: number;
    "workingDir"?: string;
    "entries"?: OutputEntry[];

    /**
     * Truncated reports that the caller already dropped output to fit the record
     * budget. The store ORs its own truncation into it, so the stored flag covers
     * losses on both sides of the binding.
     */
    "truncated"?: boolean;

    /** Creates a new RecordInput instance. */
    constructor($$source: Partial<RecordInput> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = RecordKind.$zero;
        }
        if (!("profileId" in $$source)) {
            this["profileId"] = "";
        }
        if (!("profileName" in $$source)) {
            this["profileName"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("exitCode" in $$source)) {
            this["exitCode"] = 0;
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = 0;
        }
        if (!("completedAt" in $$source)) {
            this["completedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecordInput instance from a string or object.
     */
    static createFrom($$source: any = {}): RecordInput {
        const $$createField9_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField9_0($$parsedSource["entries"]);
        }
        return new RecordInput($$parsedSource as Partial<RecordInput>);
    }
}

export enum RecordKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RecordKindOrdinary = "ordinary",
    RecordKindCompoundAggregate = "compound-aggregate",
    RecordKindCompoundStep = "compound-step",
};

export class Snapshot {
    "version": number;
    "summaries": Summary[];
    "warning"?: string;

    /** Creates a new Snapshot instance. */
    constructor($$source: Partial<Snapshot> = {}) {
        if (!("version" in $$source)) {
            this["version"] = 0;
        }
        if (!("summaries" in $$source)) {
            this["summaries"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): Snapshot {
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("summaries" in $$parsedSource) {
            $$parsedSource["summaries"] = $$createField1_0($$parsedSource["summaries"]);
        }
        return new Snapshot($$parsedSource as Partial<Snapshot>);
    }
}

export class Summary {
    "historyId": string;
    "kind": RecordKind;
    "profileId": string;
    "profileName": string;
    "state": string;
    "exitCode": number;
    "startedAt": number;
    "completedAt": number;
    "outputAvailable": boolean;

    /**
     * Truncated marks a record whose saved output is a prefix of what the run
     * actually produced. It rides on the summary (not just the record) so the
     * index carries it and the UI can warn before loading, which matters most for
     * Diff: comparing a truncated run against a complete one invents differences.
     */
    "truncated"?: boolean;

    /** Creates a new Summary instance. */
    constructor($$source: Partial<Summary> = {}) {
        if (!("historyId" in $$source)) {
            this["historyId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = RecordKind.$zero;
        }
        if (!("profileId" in $$source)) {
            this["profileId"] = "";
        }
        if (!("profileName" in $$source)) {
            this["profileName"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("exitCode" in $$source)) {
            this["exitCode"] = 0;
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = 0;
        }
        if (!("completedAt" in $$source)) {
            this["completedAt"] = 0;
        }
        if (!("outputAvailable" in $$source)) {
            this["outputAvailable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Summary instance from a string or object.
     */
    static createFrom($$source: any = {}): Summary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Summary($$parsedSource as Partial<Summary>);
    }
}

// Private type creation functions
const $$createType0 = OutputEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = Summary.createFrom;
const $$createType3 = $Create.Array($$createType2);
