// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FileResult groups all matching lines for a single file.
 *
 * Path is the absolute path. RelativePath is the path relative to the search
 * root, using forward slashes regardless of host OS so the frontend can
 * render and compare it consistently.
 */
export class FileResult {
    "path": string;
    "relativePath": string;
    "matches": LineMatch[];

    /** Creates a new FileResult instance. */
    constructor($$source: Partial<FileResult> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("relativePath" in $$source)) {
            this["relativePath"] = "";
        }
        if (!("matches" in $$source)) {
            this["matches"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileResult instance from a string or object.
     */
    static createFrom($$source: any = {}): FileResult {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("matches" in $$parsedSource) {
            $$parsedSource["matches"] = $$createField2_0($$parsedSource["matches"]);
        }
        return new FileResult($$parsedSource as Partial<FileResult>);
    }
}

/**
 * LineMatch is a single matching line within a file.
 *
 * Line is 1-based to match user-visible line numbering and the existing
 * navigateToEditorLocation contract.
 *
 * Column is the 1-based byte column of the first match on the line as
 * reported by ripgrep. Frontend converts to a character column before
 * passing to the editor.
 *
 * Submatches are ordered by Start ascending and never overlap each other
 * (ripgrep guarantees this).
 */
export class LineMatch {
    "line": number;
    "column": number;
    "text": string;
    "submatches": MatchRange[];

    /** Creates a new LineMatch instance. */
    constructor($$source: Partial<LineMatch> = {}) {
        if (!("line" in $$source)) {
            this["line"] = 0;
        }
        if (!("column" in $$source)) {
            this["column"] = 0;
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("submatches" in $$source)) {
            this["submatches"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LineMatch instance from a string or object.
     */
    static createFrom($$source: any = {}): LineMatch {
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("submatches" in $$parsedSource) {
            $$parsedSource["submatches"] = $$createField3_0($$parsedSource["submatches"]);
        }
        return new LineMatch($$parsedSource as Partial<LineMatch>);
    }
}

/**
 * MatchRange is a half-open byte range [Start, End) inside the matched line's
 * raw bytes, exactly as reported by ripgrep. The frontend converts these to
 * JS string offsets before rendering. We do not pre-convert in Go because
 * ripgrep already speaks bytes and the editor needs character offsets.
 */
export class MatchRange {
    "start": number;
    "end": number;

    /** Creates a new MatchRange instance. */
    constructor($$source: Partial<MatchRange> = {}) {
        if (!("start" in $$source)) {
            this["start"] = 0;
        }
        if (!("end" in $$source)) {
            this["end"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MatchRange instance from a string or object.
     */
    static createFrom($$source: any = {}): MatchRange {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MatchRange($$parsedSource as Partial<MatchRange>);
    }
}

/**
 * SearchOptions toggles ripgrep behavior. They map directly to ripgrep flags
 * in runner.go; they are not interpolated into a command string.
 */
export class SearchOptions {
    /**
     * Regex when true treats Query as a regular expression. When false, Query
     * is treated as a literal string (--fixed-strings).
     */
    "regex": boolean;

    /**
     * CaseSensitive when true enforces --case-sensitive. When false enforces
     * --ignore-case. ripgrep's default smart-case behavior is intentionally
     * not exposed: the IDE always sends a deterministic choice.
     */
    "caseSensitive": boolean;

    /**
     * WholeWord when true adds --word-regexp.
     */
    "wholeWord": boolean;

    /** Creates a new SearchOptions instance. */
    constructor($$source: Partial<SearchOptions> = {}) {
        if (!("regex" in $$source)) {
            this["regex"] = false;
        }
        if (!("caseSensitive" in $$source)) {
            this["caseSensitive"] = false;
        }
        if (!("wholeWord" in $$source)) {
            this["wholeWord"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchOptions($$parsedSource as Partial<SearchOptions>);
    }
}

/**
 * SearchRequest is the input shape for SearchWorkspace.
 *
 * RequestID is supplied by the caller (the frontend) so concurrent searches
 * can be tracked and canceled deterministically. It must be non-empty.
 *
 * Root must be a non-empty absolute path that exists and is a directory.
 *
 * Query is the user-entered search string. With Options.Regex == false it is
 * treated as a literal via ripgrep's --fixed-strings flag, so regex
 * metacharacters are safe.
 */
export class SearchRequest {
    "requestId": string;
    "root": string;
    "query": string;
    "options": SearchOptions;

    /** Creates a new SearchRequest instance. */
    constructor($$source: Partial<SearchRequest> = {}) {
        if (!("requestId" in $$source)) {
            this["requestId"] = "";
        }
        if (!("root" in $$source)) {
            this["root"] = "";
        }
        if (!("query" in $$source)) {
            this["query"] = "";
        }
        if (!("options" in $$source)) {
            this["options"] = (new SearchOptions());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchRequest {
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField3_0($$parsedSource["options"]);
        }
        return new SearchRequest($$parsedSource as Partial<SearchRequest>);
    }
}

/**
 * SearchResponse is the terminal result of a search request.
 *
 * Status is always set. When Status is StatusFailed, StatusMissingTool, or
 * StatusInvalidRegex, Message contains an actionable description. For other
 * statuses Message is empty.
 *
 * Truncated is true when the runner stopped collecting results because the
 * configured cap was reached. The Files slice is a prefix of all matches in
 * that case.
 *
 * MatchCap is the cap that was in effect for this request, surfaced so the
 * UI can explain "showing first N of many" without hard-coding a value.
 *
 * DurationMs is the wall-clock duration of the run in milliseconds, useful
 * for surfacing search latency.
 */
export class SearchResponse {
    "requestId": string;
    "status": SearchStatus;
    "message"?: string;
    "files": FileResult[];
    "totalFiles": number;
    "totalLines": number;
    "truncated": boolean;
    "matchCap": number;
    "durationMs": number;

    /** Creates a new SearchResponse instance. */
    constructor($$source: Partial<SearchResponse> = {}) {
        if (!("requestId" in $$source)) {
            this["requestId"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = SearchStatus.$zero;
        }
        if (!("files" in $$source)) {
            this["files"] = [];
        }
        if (!("totalFiles" in $$source)) {
            this["totalFiles"] = 0;
        }
        if (!("totalLines" in $$source)) {
            this["totalLines"] = 0;
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }
        if (!("matchCap" in $$source)) {
            this["matchCap"] = 0;
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchResponse {
        const $$createField3_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField3_0($$parsedSource["files"]);
        }
        return new SearchResponse($$parsedSource as Partial<SearchResponse>);
    }
}

/**
 * SearchStatus is a typed enumeration of terminal states for a search request.
 *
 * The frontend uses this value to render distinct UI states. We intentionally
 * avoid surfacing a generic "error" status: each failure mode that the user
 * can act on has a dedicated value.
 */
export enum SearchStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * StatusSuccess indicates ripgrep ran successfully and at least one match
     * was returned (or zero matches but ripgrep itself succeeded — see also
     * StatusNoMatches for the explicit empty case).
     */
    StatusSuccess = "success",

    /**
     * StatusNoMatches indicates ripgrep ran successfully and produced no
     * matches. This is exit code 1 from ripgrep, which is a successful empty
     * response, not a failure.
     */
    StatusNoMatches = "no_matches",

    /**
     * StatusMissingTool indicates the ripgrep binary could not be located on
     * PATH. The UI should show an actionable message ("install ripgrep")
     * rather than treating this as zero results.
     */
    StatusMissingTool = "missing_tool",

    /**
     * StatusInvalidRegex indicates ripgrep rejected the supplied query as a
     * malformed regular expression. The UI should surface the message and
     * ask the user to fix the query.
     */
    StatusInvalidRegex = "invalid_regex",

    /**
     * StatusCanceled indicates the request was canceled by the caller (for
     * example because a newer search request superseded it).
     */
    StatusCanceled = "canceled",

    /**
     * StatusFailed indicates a real failure: ripgrep exited with code 2,
     * emitted malformed JSON, or the runner could not start the process.
     * The Message field on SearchResponse carries diagnostic detail.
     */
    StatusFailed = "failed",
};

// Private type creation functions
const $$createType0 = LineMatch.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = MatchRange.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = SearchOptions.createFrom;
const $$createType5 = FileResult.createFrom;
const $$createType6 = $Create.Array($$createType5);
