// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * EnvVariant represents an alternative environment configuration.
 */
export class EnvVariant {
    "name": string;
    "envFile": string;

    /** Creates a new EnvVariant instance. */
    constructor($$source: Partial<EnvVariant> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("envFile" in $$source)) {
            this["envFile"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnvVariant instance from a string or object.
     */
    static createFrom($$source: any = {}): EnvVariant {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EnvVariant($$parsedSource as Partial<EnvVariant>);
    }
}

/**
 * EnvVariants stores environment variants in the canonical array shape while
 * still accepting the issue #64 map shape from hand-written profile files.
 */
export type EnvVariants = EnvVariant[];

/**
 * ProfileSource distinguishes user-created profiles from auto-detected ones.
 */
export enum ProfileSource {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ProfileSourceUser = "user",
    ProfileSourceDetected = "detected",
};

/**
 * ProfileTag categorizes profiles for filtering and display.
 */
export enum ProfileTag {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TagBuild = "build",
    TagTest = "test",
    TagDev = "dev",
    TagDeploy = "deploy",
    TagLint = "lint",
};

/**
 * ProfileType distinguishes single-command profiles from compound (multi-step) profiles.
 */
export enum ProfileType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ProfileTypeSingle = "single",
    ProfileTypeCompound = "compound",
};

/**
 * ProfileUIState is per-workspace, per-profile working-set state: whether a
 * detected profile has been adopted into the working set, and when it last ran.
 * Both fields are additive (P2); a v2 file loads with an empty ProfileState map.
 */
export class ProfileUIState {
    "adopted"?: boolean;
    "lastRunAt"?: number;

    /** Creates a new ProfileUIState instance. */
    constructor($$source: Partial<ProfileUIState> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileUIState instance from a string or object.
     */
    static createFrom($$source: any = {}): ProfileUIState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProfileUIState($$parsedSource as Partial<ProfileUIState>);
    }
}

/**
 * RunProfile represents a single run configuration.
 */
export class RunProfile {
    "id": string;
    "name": string;
    "type": ProfileType;
    "source": ProfileSource;
    "command"?: string;
    "workingDir"?: string;
    "env"?: { [_ in string]?: string };
    "envFile"?: string;
    "envVariants"?: EnvVariants;
    "activeVariant"?: string;
    "tags"?: ProfileTag[];
    "steps"?: string[];
    "detectedFrom"?: string;
    "order"?: number;

    /**
     * owner: "frontend" | "root:go" | "project"
     */
    "workspaceId"?: string;

    /**
     * display label, e.g. "Frontend"
     */
    "workspaceName"?: string;

    /**
     * "" for repo-root profiles
     */
    "workspaceRelDir"?: string;

    /** Creates a new RunProfile instance. */
    constructor($$source: Partial<RunProfile> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = ProfileType.$zero;
        }
        if (!("source" in $$source)) {
            this["source"] = ProfileSource.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunProfile instance from a string or object.
     */
    static createFrom($$source: any = {}): RunProfile {
        const $$createField6_0 = $$createType0;
        const $$createField8_0 = $$createType1;
        const $$createField10_0 = $$createType4;
        const $$createField11_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("env" in $$parsedSource) {
            $$parsedSource["env"] = $$createField6_0($$parsedSource["env"]);
        }
        if ("envVariants" in $$parsedSource) {
            $$parsedSource["envVariants"] = $$createField8_0($$parsedSource["envVariants"]);
        }
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField10_0($$parsedSource["tags"]);
        }
        if ("steps" in $$parsedSource) {
            $$parsedSource["steps"] = $$createField11_0($$parsedSource["steps"]);
        }
        return new RunProfile($$parsedSource as Partial<RunProfile>);
    }
}

/**
 * RunProfilesSnapshot is the combined repo-wide view consumed by the frontend:
 * the merged profile list plus per-profile UI state keyed by (globally unique)
 * profile ID. It is the single hydration contract for initial load and the
 * runprofiles:changed event.
 */
export class RunProfilesSnapshot {
    "profiles": RunProfile[];
    "profileState": { [_ in string]?: ProfileUIState };
    "workspaceEpoch": number;

    /** Creates a new RunProfilesSnapshot instance. */
    constructor($$source: Partial<RunProfilesSnapshot> = {}) {
        if (!("profiles" in $$source)) {
            this["profiles"] = [];
        }
        if (!("profileState" in $$source)) {
            this["profileState"] = {};
        }
        if (!("workspaceEpoch" in $$source)) {
            this["workspaceEpoch"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunProfilesSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): RunProfilesSnapshot {
        const $$createField0_0 = $$createType7;
        const $$createField1_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("profiles" in $$parsedSource) {
            $$parsedSource["profiles"] = $$createField0_0($$parsedSource["profiles"]);
        }
        if ("profileState" in $$parsedSource) {
            $$parsedSource["profileState"] = $$createField1_0($$parsedSource["profileState"]);
        }
        return new RunProfilesSnapshot($$parsedSource as Partial<RunProfilesSnapshot>);
    }
}

/**
 * RunState represents the lifecycle state of a profile execution.
 */
export enum RunState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RunStateIdle = "idle",
    RunStateRunning = "running",

    /**
     * user-initiated stop
     */
    RunStateStopped = "stopped",

    /**
     * non-zero exit code
     */
    RunStateFailed = "failed",

    /**
     * exit code 0
     */
    RunStateSuccess = "success",
};

/**
 * RunStatus is emitted to the frontend on every state transition.
 */
export class RunStatus {
    "runInstanceId": string;
    "profileId": string;
    "parentRunInstanceId"?: string;
    "stepIdx": number;
    "workspaceEpoch": number;
    "launchSeq": number;
    "state": RunState;
    "exitCode": number;
    "pid"?: number;
    "timestamp": number;
    "reason"?: string;

    /** Creates a new RunStatus instance. */
    constructor($$source: Partial<RunStatus> = {}) {
        if (!("runInstanceId" in $$source)) {
            this["runInstanceId"] = "";
        }
        if (!("profileId" in $$source)) {
            this["profileId"] = "";
        }
        if (!("stepIdx" in $$source)) {
            this["stepIdx"] = 0;
        }
        if (!("workspaceEpoch" in $$source)) {
            this["workspaceEpoch"] = 0;
        }
        if (!("launchSeq" in $$source)) {
            this["launchSeq"] = 0;
        }
        if (!("state" in $$source)) {
            this["state"] = RunState.$zero;
        }
        if (!("exitCode" in $$source)) {
            this["exitCode"] = 0;
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): RunStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RunStatus($$parsedSource as Partial<RunStatus>);
    }
}

/**
 * ValidationError describes a single validation failure.
 */
export class ValidationError {
    "field": string;
    "message": string;

    /** Creates a new ValidationError instance. */
    constructor($$source: Partial<ValidationError> = {}) {
        if (!("field" in $$source)) {
            this["field"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ValidationError instance from a string or object.
     */
    static createFrom($$source: any = {}): ValidationError {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ValidationError($$parsedSource as Partial<ValidationError>);
    }
}

/**
 * ValidationResult holds the outcome of profile validation.
 */
export class ValidationResult {
    "valid": boolean;
    "errors": ValidationError[];

    /** Creates a new ValidationResult instance. */
    constructor($$source: Partial<ValidationResult> = {}) {
        if (!("valid" in $$source)) {
            this["valid"] = false;
        }
        if (!("errors" in $$source)) {
            this["errors"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ValidationResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ValidationResult {
        const $$createField1_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField1_0($$parsedSource["errors"]);
        }
        return new ValidationResult($$parsedSource as Partial<ValidationResult>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
var $$createType1 = (function $$initCreateType1(...args: any[]): any {
    if ($$createType1 === $$initCreateType1) {
        $$createType1 = $$createType3;
    }
    return $$createType1(...args);
});
const $$createType2 = EnvVariant.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = RunProfile.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = ProfileUIState.createFrom;
const $$createType9 = $Create.Map($Create.Any, $$createType8);
const $$createType10 = ValidationError.createFrom;
const $$createType11 = $Create.Array($$createType10);
