module.exports = {
  EventsOn: jest.fn(() => jest.fn()),
  EventsOnce: jest.fn(() => jest.fn()),
  EventsOnMultiple: jest.fn(() => jest.fn()),
  EventsOff: jest.fn(),
  EventsOffAll: jest.fn(),
  EventsEmit: jest.fn(),
  WindowSetTitle: jest.fn(),
  BrowserOpenURL: jest.fn(),
  ClipboardSetText: jest.fn(() => Promise.resolve()),
  LogPrint: jest.fn(),
  LogTrace: jest.fn(),
  LogDebug: jest.fn(),
  LogInfo: jest.fn(),
  LogWarning: jest.fn(),
  LogError: jest.fn(),
  LogFatal: jest.fn(),
};
