// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetWatchedPath() {
  return window['go']['main']['App']['GetWatchedPath']();
}

export function GetWorkspaceInfo() {
  return window['go']['main']['App']['GetWorkspaceInfo']();
}

export function IsWatching() {
  return window['go']['main']['App']['IsWatching']();
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function ReadDirectory(arg1) {
  return window['go']['main']['App']['ReadDirectory'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function StartWatching(arg1) {
  return window['go']['main']['App']['StartWatching'](arg1);
}

export function StopWatching() {
  return window['go']['main']['App']['StopWatching']();
}

export function ToggleMaximize() {
  return window['go']['main']['App']['ToggleMaximize']();
}

export function WriteFile(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2, arg3, arg4, arg5);
}
