// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {filesystem} from '../models';

export function GetWatchedPath():Promise<string>;

export function GetWorkspaceInfo():Promise<main.WorkspaceInfo>;

export function IsWatching():Promise<boolean>;

export function OpenFolderDialog():Promise<string>;

export function ReadDirectory(arg1:string):Promise<Array<filesystem.FileEntry>>;

export function ReadFile(arg1:string):Promise<filesystem.FileContent>;

export function StartWatching(arg1:string):Promise<void>;

export function StopWatching():Promise<void>;

export function ToggleMaximize():Promise<void>;

export function WriteFile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;
