// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelSearch(arg1) {
  return window['go']['main']['App']['CancelSearch'](arg1);
}

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function ConfirmBeforeCloseReady() {
  return window['go']['main']['App']['ConfirmBeforeCloseReady']();
}

export function CreateTerminal() {
  return window['go']['main']['App']['CreateTerminal']();
}

export function DeleteRunProfile(arg1) {
  return window['go']['main']['App']['DeleteRunProfile'](arg1);
}

export function DetectRunProfiles() {
  return window['go']['main']['App']['DetectRunProfiles']();
}

export function DetectWorkspaces(arg1) {
  return window['go']['main']['App']['DetectWorkspaces'](arg1);
}

export function GetAllRunProfiles() {
  return window['go']['main']['App']['GetAllRunProfiles']();
}

export function GetLSPStatus() {
  return window['go']['main']['App']['GetLSPStatus']();
}

export function GetRunStatus(arg1) {
  return window['go']['main']['App']['GetRunStatus'](arg1);
}

export function GetWatchedPath() {
  return window['go']['main']['App']['GetWatchedPath']();
}

export function GetWorkspaceInfo() {
  return window['go']['main']['App']['GetWorkspaceInfo']();
}

export function IsWatching() {
  return window['go']['main']['App']['IsWatching']();
}

export function LSPComplete(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LSPComplete'](arg1, arg2, arg3, arg4);
}

export function LSPDefinition(arg1, arg2, arg3) {
  return window['go']['main']['App']['LSPDefinition'](arg1, arg2, arg3);
}

export function LSPDidChange(arg1, arg2, arg3) {
  return window['go']['main']['App']['LSPDidChange'](arg1, arg2, arg3);
}

export function LSPDidClose(arg1) {
  return window['go']['main']['App']['LSPDidClose'](arg1);
}

export function LSPDidOpen(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LSPDidOpen'](arg1, arg2, arg3, arg4);
}

export function LSPDidSave(arg1) {
  return window['go']['main']['App']['LSPDidSave'](arg1);
}

export function LSPHover(arg1, arg2, arg3) {
  return window['go']['main']['App']['LSPHover'](arg1, arg2, arg3);
}

export function LSPResolveCompletionItem(arg1, arg2) {
  return window['go']['main']['App']['LSPResolveCompletionItem'](arg1, arg2);
}

export function ListRecentWorkspaces() {
  return window['go']['main']['App']['ListRecentWorkspaces']();
}

export function LoadRunProfiles(arg1) {
  return window['go']['main']['App']['LoadRunProfiles'](arg1);
}

export function LoadWorkspaceState(arg1) {
  return window['go']['main']['App']['LoadWorkspaceState'](arg1);
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function PinRunProfile(arg1) {
  return window['go']['main']['App']['PinRunProfile'](arg1);
}

export function ReadDirectory(arg1) {
  return window['go']['main']['App']['ReadDirectory'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function RestartRunProfile(arg1) {
  return window['go']['main']['App']['RestartRunProfile'](arg1);
}

export function SaveRunProfile(arg1) {
  return window['go']['main']['App']['SaveRunProfile'](arg1);
}

export function SaveWorkspaceState(arg1) {
  return window['go']['main']['App']['SaveWorkspaceState'](arg1);
}

export function SearchWorkspace(arg1) {
  return window['go']['main']['App']['SearchWorkspace'](arg1);
}

export function SetActiveVariant(arg1, arg2) {
  return window['go']['main']['App']['SetActiveVariant'](arg1, arg2);
}

export function SetLSPWorkspaceRoot(arg1) {
  return window['go']['main']['App']['SetLSPWorkspaceRoot'](arg1);
}

export function StartRunProfile(arg1) {
  return window['go']['main']['App']['StartRunProfile'](arg1);
}

export function StartWatching(arg1) {
  return window['go']['main']['App']['StartWatching'](arg1);
}

export function StopRunProfile(arg1) {
  return window['go']['main']['App']['StopRunProfile'](arg1);
}

export function StopWatching() {
  return window['go']['main']['App']['StopWatching']();
}

export function ToggleMaximize() {
  return window['go']['main']['App']['ToggleMaximize']();
}

export function UnpinRunProfile(arg1) {
  return window['go']['main']['App']['UnpinRunProfile'](arg1);
}

export function ValidateRunProfile(arg1) {
  return window['go']['main']['App']['ValidateRunProfile'](arg1);
}

export function WriteFile(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2, arg3, arg4, arg5);
}

export function WriteTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteTerminal'](arg1, arg2);
}
