// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {runprofile} from '../models';
import {main} from '../models';
import {workspace} from '../models';
import {filesystem} from '../models';

export function CloseTerminal(arg1:string):Promise<void>;

export function ConfirmBeforeCloseReady():Promise<void>;

export function CreateTerminal():Promise<string>;

export function DeleteRunProfile(arg1:string):Promise<void>;

export function DetectRunProfiles():Promise<Array<runprofile.RunProfile>>;

export function GetAllRunProfiles():Promise<Array<runprofile.RunProfile>>;

export function GetRunStatus(arg1:string):Promise<runprofile.RunStatus>;

export function GetWatchedPath():Promise<string>;

export function GetWorkspaceInfo():Promise<main.WorkspaceInfo>;

export function IsWatching():Promise<boolean>;

export function ListRecentWorkspaces():Promise<Array<workspace.Summary>>;

export function LoadRunProfiles(arg1:string):Promise<void>;

export function LoadWorkspaceState(arg1:string):Promise<workspace.State>;

export function OpenFolderDialog():Promise<string>;

export function PinRunProfile(arg1:string):Promise<void>;

export function ReadDirectory(arg1:string):Promise<Array<filesystem.FileEntry>>;

export function ReadFile(arg1:string):Promise<filesystem.FileContent>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RestartRunProfile(arg1:string):Promise<void>;

export function SaveRunProfile(arg1:runprofile.RunProfile):Promise<runprofile.ValidationResult>;

export function SaveWorkspaceState(arg1:workspace.State):Promise<void>;

export function StartRunProfile(arg1:string):Promise<void>;

export function StartWatching(arg1:string):Promise<void>;

export function StopRunProfile(arg1:string):Promise<void>;

export function StopWatching():Promise<void>;

export function ToggleMaximize():Promise<void>;

export function ValidateRunProfile(arg1:runprofile.RunProfile):Promise<runprofile.ValidationResult>;

export function WriteFile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function WriteTerminal(arg1:string,arg2:string):Promise<void>;
